# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "resources/applications"
require_relative "resources/balances"
require_relative "resources/cards"
require_relative "resources/companies"
require_relative "resources/contracts"
require_relative "resources/disputes"
require_relative "resources/keys"
require_relative "resources/payments"
require_relative "resources/signatures"
require_relative "resources/transactions"
require_relative "resources/users"

module Redrain
  class Client
    # @return [Resources::Applications] the applications resource, memoised
    def applications = @resources[:applications] ||= Resources::Applications.new(self)
    # @return [Resources::Balances] the balances resource, memoised
    def balances = @resources[:balances] ||= Resources::Balances.new(self)
    # @return [Resources::Cards] the cards resource, memoised
    def cards = @resources[:cards] ||= Resources::Cards.new(self)
    # @return [Resources::Companies] the companies resource, memoised
    def companies = @resources[:companies] ||= Resources::Companies.new(self)
    # @return [Resources::Contracts] the contracts resource, memoised
    def contracts = @resources[:contracts] ||= Resources::Contracts.new(self)
    # @return [Resources::Disputes] the disputes resource, memoised
    def disputes = @resources[:disputes] ||= Resources::Disputes.new(self)
    # @return [Resources::Keys] the keys resource, memoised
    def keys = @resources[:keys] ||= Resources::Keys.new(self)
    # @return [Resources::Payments] the payments resource, memoised
    def payments = @resources[:payments] ||= Resources::Payments.new(self)
    # @return [Resources::Signatures] the signatures resource, memoised
    def signatures = @resources[:signatures] ||= Resources::Signatures.new(self)
    # @return [Resources::Transactions] the transactions resource, memoised
    def transactions = @resources[:transactions] ||= Resources::Transactions.new(self)
    # @return [Resources::Users] the users resource, memoised
    def users = @resources[:users] ||= Resources::Users.new(self)
  end
end
