# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "resources/applications"
require_relative "resources/balances"
require_relative "resources/cards"
require_relative "resources/companies"
require_relative "resources/contracts"
require_relative "resources/disputes"
require_relative "resources/keys"
require_relative "resources/payments"
require_relative "resources/signatures"
require_relative "resources/transactions"
require_relative "resources/users"

module Redrain
  class Client
    # @return [Resources::ApplicationsResource] the applications resource, memoised
    def applications = @resources[:applications] ||= Resources::ApplicationsResource.new(self)
    # @return [Resources::BalancesResource] the balances resource, memoised
    def balances = @resources[:balances] ||= Resources::BalancesResource.new(self)
    # @return [Resources::CardsResource] the cards resource, memoised
    def cards = @resources[:cards] ||= Resources::CardsResource.new(self)
    # @return [Resources::CompaniesResource] the companies resource, memoised
    def companies = @resources[:companies] ||= Resources::CompaniesResource.new(self)
    # @return [Resources::ContractsResource] the contracts resource, memoised
    def contracts = @resources[:contracts] ||= Resources::ContractsResource.new(self)
    # @return [Resources::DisputesResource] the disputes resource, memoised
    def disputes = @resources[:disputes] ||= Resources::DisputesResource.new(self)
    # @return [Resources::KeysResource] the keys resource, memoised
    def keys = @resources[:keys] ||= Resources::KeysResource.new(self)
    # @return [Resources::PaymentsResource] the payments resource, memoised
    def payments = @resources[:payments] ||= Resources::PaymentsResource.new(self)
    # @return [Resources::SignaturesResource] the signatures resource, memoised
    def signatures = @resources[:signatures] ||= Resources::SignaturesResource.new(self)
    # @return [Resources::TransactionsResource] the transactions resource, memoised
    def transactions = @resources[:transactions] ||= Resources::TransactionsResource.new(self)
    # @return [Resources::UsersResource] the users resource, memoised
    def users = @resources[:users] ||= Resources::UsersResource.new(self)
  end
end
