# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents the possible statuses of an application.
  # One of: approved, pending, needsInformation, needsVerification, manualReview, denied,
  # locked, canceled
  module ApplicationStatus
    # @return [Array<String>] every value Rain documents for this field
    VALUES = %w[approved pending needsInformation needsVerification manualReview denied locked canceled].freeze
  end
end
