# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # The encrypted data for the card
  class CardRetrieveSecretsResponse < Model
    # The encrypted PAN
    class EncryptedPan < Model
      # The initialization vector
      # @!attribute [r] iv
      # @return [String, nil] always present in a successful response
      field :iv, :string

      # The encrypted data
      # @!attribute [r] data
      # @return [String, nil] always present in a successful response
      field :data, :string
    end

    # The encrypted CVC
    class EncryptedCvc < Model
      # The initialization vector
      # @!attribute [r] iv
      # @return [String, nil] always present in a successful response
      field :iv, :string

      # The encrypted data
      # @!attribute [r] data
      # @return [String, nil] always present in a successful response
      field :data, :string
    end

    # The encrypted PAN
    # @!attribute [r] encrypted_pan
    # @return [Redrain::EncryptedPan, nil] always present in a successful response
    field :encrypted_pan, EncryptedPan, api: "encryptedPan"

    # The encrypted CVC
    # @!attribute [r] encrypted_cvc
    # @return [Redrain::EncryptedCvc, nil] always present in a successful response
    field :encrypted_cvc, EncryptedCvc, api: "encryptedCvc"
  end
end
