# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A CompanyInitiatePaymentResponse record.
  class CompanyInitiatePaymentResponse < Model
    # The address to send the payment to
    # @!attribute [r] address
    # @return [String, nil] always present in a successful response
    field :address, :string
  end
end
