# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A CompanyRetrieveResponse record.
  class CompanyRetrieveResponse < IssuingApplication
    # The nested UltimateBeneficialOwner object carried by CompanyRetrieveResponse.
    class UltimateBeneficialOwner < Model
      # The UBO's unique identifier
      # @!attribute [r] id
      # @return [String, nil] always present in a successful response
      field :id, :string

      # The UBO's first name
      # @!attribute [r] first_name
      # @return [String, nil]
      field :first_name, :string, api: "firstName"

      # The UBO's last name
      # @!attribute [r] last_name
      # @return [String, nil]
      field :last_name, :string, api: "lastName"

      # The UBO's email address
      # @!attribute [r] email
      # @return [String, nil]
      field :email, :string
    end

    # The identifier of the company application
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The company's ultimate beneficial owners (UBOs)
    # @!attribute [r] ultimate_beneficial_owners
    # @return [Array<Redrain::UltimateBeneficialOwner>, nil] always present in a successful response
    field :ultimate_beneficial_owners, [UltimateBeneficialOwner], api: "ultimateBeneficialOwners"
  end
end
