# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents the response body returned after a charge is created, including the charge ID,
  # creation timestamp, and charge details.
  class IssuingChargeCreateChargeResponse < Model
    # The identifier of the charge
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The date and time when the charge was created
    # @!attribute [r] created_at
    # @return [Time, nil] always present in a successful response
    field :created_at, :time, api: "createdAt"

    # The amount of the charge, in cents
    # @!attribute [r] amount
    # @return [Integer, nil]
    field :amount, :integer

    # The description of the charge
    # @!attribute [r] description
    # @return [String, nil]
    field :description, :string
  end
end
