# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents a dispute related to an issuing transaction.
  class IssuingDispute < Model
    # The dispute's unique identifier
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The transaction's unique identifier
    # @!attribute [r] transaction_id
    # @return [String, nil] always present in a successful response
    field :transaction_id, :string, api: "transactionId"

    # The current status of the dispute
    # One of: pending, inReview, accepted, rejected, canceled
    # @!attribute [r] status
    # @return [String, nil] always present in a successful response
    field :status, :string

    # Textual evidence provided by the parties involved in the dispute
    # @!attribute [r] text_evidence
    # @return [String, nil]
    field :text_evidence, :string, api: "textEvidence"

    # The date and time when the dispute was created
    # @!attribute [r] created_at
    # @return [Time, nil] always present in a successful response
    field :created_at, :time, api: "createdAt"

    # The date and time when the dispute was resolved, if applicable
    # @!attribute [r] resolved_at
    # @return [Time, nil]
    field :resolved_at, :time, api: "resolvedAt"
  end
end
