# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingSignature record.
  class IssuingSignature < Model
    # The nested Signature object carried by IssuingSignature.
    class Signature < Model
      # The actual signature data
      # @!attribute [r] data
      # @return [String, nil] always present in a successful response
      field :data, :string

      # The salt used to generate the signature
      # @!attribute [r] salt
      # @return [String, nil] always present in a successful response
      field :salt, :string
    end

    # Which variant this record is, read from `status`.
    VARIANTS = %w[pending ready].freeze

    # Which kind of record this is, and therefore which of the detail fields is populated
    # One of: pending, ready
    # @!attribute [r] status
    # @return [String, nil] always present in a successful response
    field :status, :string

    # The number of seconds after which the signature can be retried
    # @!attribute [r] retry_after
    # @return [Integer, nil]
    field :retry_after, :integer, api: "retryAfter"

    # @!attribute [r] signature
    # @return [Redrain::Signature, nil]
    field :signature, Signature

    # The time at which the signature will expire
    # @!attribute [r] expires_at
    # @return [Time, nil]
    field :expires_at, :time, api: "expiresAt"

    # @return [Boolean] true when `status` is "pending"
    def pending? = status == "pending"
    # @return [Boolean] true when `status` is "ready"
    def ready? = status == "ready"
  end
end
