# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # The current status of the card
  # One of: notActivated, active, locked, canceled
  module IssuingCardStatus
    # @return [Array<String>] every value Rain documents for this field
    VALUES = %w[notActivated active locked canceled].freeze
  end
end
