# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingCard record.
  class IssuingCard < Model
    # The card's ID
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The ID of the company that issued the card
    # @!attribute [r] company_id
    # @return [String, nil] always present in a successful response
    field :company_id, :string, api: "companyId"

    # The userID to whom the card was issued
    # @!attribute [r] user_id
    # @return [String, nil] always present in a successful response
    field :user_id, :string, api: "userId"

    # The type of the card (physical or virtual)
    # One of: physical, virtual
    # @!attribute [r] type
    # @return [String, nil] always present in a successful response
    field :type, :string

    # The card's current status
    # One of: notActivated, active, locked, canceled
    # @!attribute [r] status
    # @return [String, nil] always present in a successful response
    field :status, :string

    # The card's spending limit
    # @!attribute [r] limit
    # @return [Redrain::IssuingCardLimit, nil]
    field :limit, IssuingCardLimit

    # The last four digits of the card number
    # @!attribute [r] last4
    # @return [String, nil] always present in a successful response
    field :last4, :string

    # The expiration month of the card
    # @!attribute [r] expiration_month
    # @return [String, nil] always present in a successful response
    field :expiration_month, :string, api: "expirationMonth"

    # The expiration year of the card
    # @!attribute [r] expiration_year
    # @return [String, nil] always present in a successful response
    field :expiration_year, :string, api: "expirationYear"

    # @!attribute [r] token_wallets
    # @return [Array<String>, nil]
    field :token_wallets, [:string], api: "tokenWallets"
  end
end
