# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents an issuing contract with details about its deployment and token handling.
  class IssuingContract < Model
    # The nested Token object carried by IssuingContract.
    class Token < Model
      # The address of the token contract
      # @!attribute [r] address
      # @return [String, nil] always present in a successful response
      field :address, :string

      # The balance of the token
      # @!attribute [r] balance
      # @return [String, nil]
      field :balance, :string

      # The exchange rate for the token
      # @!attribute [r] exchange_rate
      # @return [Float, nil]
      field :exchange_rate, :number, api: "exchangeRate"

      # The advance rate for the token
      # @!attribute [r] advance_rate
      # @return [Float, nil]
      field :advance_rate, :number, api: "advanceRate"
    end

    # The contract's unique identifier
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The chain ID (base-10 number) that the smart contract is deployed on
    # @!attribute [r] chain_id
    # @return [Integer, nil] always present in a successful response
    field :chain_id, :integer, api: "chainId"

    # The address of the contract's controller
    # @!attribute [r] controller_address
    # @return [String, nil] always present in a successful response
    field :controller_address, :string, api: "controllerAddress"

    # The proxy address of the contract
    # @!attribute [r] proxy_address
    # @return [String, nil] always present in a successful response
    field :proxy_address, :string, api: "proxyAddress"

    # The address where funds should be deposited
    # @!attribute [r] deposit_address
    # @return [String, nil]
    field :deposit_address, :string, api: "depositAddress"

    # Tokens that the contract accepts for transactions
    # @!attribute [r] tokens
    # @return [Array<Redrain::Token>, nil] always present in a successful response
    field :tokens, [Token]

    # Version of the contract
    # @!attribute [r] contract_version
    # @return [Integer, nil] always present in a successful response
    field :contract_version, :integer, api: "contractVersion"
  end
end
