# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # The details of an issuing application.
  class IssuingApplication < Model
    # The nested Params object carried by IssuingApplication.
    class Params < Model
      # The user's unique identifier
      # @!attribute [r] user_id
      # @return [String, nil]
      field :user_id, :string, api: "userId"
    end

    # The link to the external verification page for the application
    class ApplicationExternalVerificationLink < Model
      # The URL for the external verification page
      # @!attribute [r] url
      # @return [String, nil] always present in a successful response
      field :url, :string

      # @!attribute [r] params
      # @return [Redrain::Params, nil]
      field :params, Params
    end

    # The link to the application completion page
    class ApplicationCompletionLink < Model
      # The URL for the completion page
      # @!attribute [r] url
      # @return [String, nil] always present in a successful response
      field :url, :string

      # @!attribute [r] params
      # @return [Redrain::Params, nil]
      field :params, Params
    end

    # One of: approved, pending, needsInformation, needsVerification, manualReview, denied,
    # locked, canceled
    # @!attribute [r] application_status
    # @return [String, nil] always present in a successful response
    field :application_status, :string, api: "applicationStatus"

    # The link to the external verification page for the application
    # @!attribute [r] application_external_verification_link
    # @return [Redrain::ApplicationExternalVerificationLink, nil]
    field :application_external_verification_link, ApplicationExternalVerificationLink, api: "applicationExternalVerificationLink"

    # The link to the application completion page
    # @!attribute [r] application_completion_link
    # @return [Redrain::ApplicationCompletionLink, nil]
    field :application_completion_link, ApplicationCompletionLink, api: "applicationCompletionLink"

    # The reason behind the current application status
    # @!attribute [r] application_reason
    # @return [String, nil]
    field :application_reason, :string, api: "applicationReason"
  end
end
