# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingApplicationPerson record.
  class IssuingApplicationPerson < Model
    # The person's unique identifier
    # @!attribute [r] id
    # @return [String, nil]
    field :id, :string

    # The person's first name
    # @!attribute [r] first_name
    # @return [String, nil] always present in a successful response
    field :first_name, :string, api: "firstName"

    # The person's last name
    # @!attribute [r] last_name
    # @return [String, nil] always present in a successful response
    field :last_name, :string, api: "lastName"

    # The person's birth date
    # @!attribute [r] birth_date
    # @return [String, nil] always present in a successful response
    field :birth_date, :string, api: "birthDate"

    # The person's national ID number. For the US, this is a 9-digit SSN
    # @!attribute [r] national_id
    # @return [String, nil] always present in a successful response
    field :national_id, :string, api: "nationalId"

    # The 2-digit country code of the person's national ID issuer
    # @!attribute [r] country_of_issue
    # @return [String, nil] always present in a successful response
    field :country_of_issue, :string, api: "countryOfIssue"

    # The user's email address
    # @!attribute [r] email
    # @return [String, nil] always present in a successful response
    field :email, :string

    # The country code for the phone number
    # @!attribute [r] phone_country_code
    # @return [String, nil]
    field :phone_country_code, :string, api: "phoneCountryCode"

    # The phone number of the person
    # @!attribute [r] phone_number
    # @return [String, nil]
    field :phone_number, :string, api: "phoneNumber"

    # The person's address
    # @!attribute [r] address
    # @return [Redrain::PhysicalAddress, nil] always present in a successful response
    field :address, PhysicalAddress
  end
end
