# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents a unique key used for issuing, typically used for authentication or encryption
  # purposes.
  class IssuingKey < Model
    # The key's unique identifier
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The actual key used for the issuing process
    # @!attribute [r] key
    # @return [String, nil] always present in a successful response
    field :key, :string

    # The name assigned to the key
    # @!attribute [r] name
    # @return [String, nil] always present in a successful response
    field :name, :string

    # The expiration date and time of the key
    # @!attribute [r] expires_at
    # @return [Time, nil] always present in a successful response
    field :expires_at, :time, api: "expiresAt"
  end
end
