# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingCompany record.
  class IssuingCompany < IssuingApplication
    # The nested UltimateBeneficialOwner object carried by IssuingCompany.
    class UltimateBeneficialOwner < Model
      # The UBO's unique identifier
      # @!attribute [r] id
      # @return [String, nil] always present in a successful response
      field :id, :string
    end

    # The company's unique identifier
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The company's name on the Rain platform
    # @!attribute [r] name
    # @return [String, nil] always present in a successful response
    field :name, :string

    # The company's physical address
    # @!attribute [r] address
    # @return [Redrain::PhysicalAddress, nil] always present in a successful response
    field :address, PhysicalAddress

    # The company's ultimate beneficial owners (UBOs)
    # @!attribute [r] ultimate_beneficial_owners
    # @return [Array<Redrain::UltimateBeneficialOwner>, nil]
    field :ultimate_beneficial_owners, [UltimateBeneficialOwner], api: "ultimateBeneficialOwners"
  end
end
