# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingTransaction record.
  class IssuingTransaction < Model
    # Details specific to a spend transaction, including merchant, amount, and user information.
    class Spend < Model
      # The amount of the transaction, in cents
      # @!attribute [r] amount
      # @return [Integer, nil] always present in a successful response
      field :amount, :integer

      # The currency of the transaction
      # @!attribute [r] currency
      # @return [String, nil] always present in a successful response
      field :currency, :string

      # The amount of the transaction in local currency, in cents
      # @!attribute [r] local_amount
      # @return [Integer, nil]
      field :local_amount, :integer, api: "localAmount"

      # The local currency of the transaction
      # @!attribute [r] local_currency
      # @return [String, nil]
      field :local_currency, :string, api: "localCurrency"

      # The authorized amount of the transaction, in cents
      # @!attribute [r] authorized_amount
      # @return [Integer, nil]
      field :authorized_amount, :integer, api: "authorizedAmount"

      # The method used for authorization of the transaction
      # @!attribute [r] authorization_method
      # @return [String, nil]
      field :authorization_method, :string, api: "authorizationMethod"

      # A memo or note associated with the transaction
      # @!attribute [r] memo
      # @return [String, nil]
      field :memo, :string

      # Indicates whether a receipt was generated for the transaction
      # @!attribute [r] receipt
      # @return [Boolean, nil] always present in a successful response
      field :receipt, :boolean

      # The name of the merchant where the transaction took place
      # @!attribute [r] merchant_name
      # @return [String, nil] always present in a successful response
      field :merchant_name, :string, api: "merchantName"

      # The category of the merchant (e.g., electronics, food)
      # @!attribute [r] merchant_category
      # @return [String, nil] always present in a successful response
      field :merchant_category, :string, api: "merchantCategory"

      # The merchant's category code
      # @!attribute [r] merchant_category_code
      # @return [String, nil] always present in a successful response
      field :merchant_category_code, :string, api: "merchantCategoryCode"

      # The enriched icon of the merchant
      # @!attribute [r] enriched_merchant_icon
      # @return [String, nil]
      field :enriched_merchant_icon, :string, api: "enrichedMerchantIcon"

      # An enriched name of the merchant, possibly with additional information
      # @!attribute [r] enriched_merchant_name
      # @return [String, nil]
      field :enriched_merchant_name, :string, api: "enrichedMerchantName"

      # An enriched category of the merchant, providing further details
      # @!attribute [r] enriched_merchant_category
      # @return [String, nil]
      field :enriched_merchant_category, :string, api: "enrichedMerchantCategory"

      # The unique identifier of the card used for the transaction
      # @!attribute [r] card_id
      # @return [String, nil] always present in a successful response
      field :card_id, :string, api: "cardId"

      # The type of card used for the transaction
      # One of: physical, virtual
      # @!attribute [r] card_type
      # @return [String, nil] always present in a successful response
      field :card_type, :string, api: "cardType"

      # The identifier of the company under which the transaction was made
      # @!attribute [r] company_id
      # @return [String, nil]
      field :company_id, :string, api: "companyId"

      # The identifier of the user who made the transaction
      # @!attribute [r] user_id
      # @return [String, nil] always present in a successful response
      field :user_id, :string, api: "userId"

      # The first name of the user who made the transaction
      # @!attribute [r] user_first_name
      # @return [String, nil] always present in a successful response
      field :user_first_name, :string, api: "userFirstName"

      # The last name of the user who made the transaction
      # @!attribute [r] user_last_name
      # @return [String, nil] always present in a successful response
      field :user_last_name, :string, api: "userLastName"

      # The email address of the user who made the transaction
      # @!attribute [r] user_email
      # @return [String, nil] always present in a successful response
      field :user_email, :string, api: "userEmail"

      # The status of the transaction
      # One of: pending, reversed, declined, completed
      # @!attribute [r] status
      # @return [String, nil] always present in a successful response
      field :status, :string

      # The reason why the transaction was declined
      # @!attribute [r] declined_reason
      # @return [String, nil]
      field :declined_reason, :string, api: "declinedReason"

      # The time at which the transaction was authorized
      # @!attribute [r] authorized_at
      # @return [String, nil] always present in a successful response
      field :authorized_at, :string, api: "authorizedAt"

      # The time at which the transaction was posted
      # @!attribute [r] posted_at
      # @return [String, nil]
      field :posted_at, :string, api: "postedAt"
    end

    # Details of the collateral transaction, including amount, currency, and transaction
    # details.
    class Collateral < Model
      # The amount of the collateral transaction, in cents
      # @!attribute [r] amount
      # @return [Float, nil] always present in a successful response
      field :amount, :number

      # The currency of the collateral transaction
      # @!attribute [r] currency
      # @return [String, nil] always present in a successful response
      field :currency, :string

      # A memo or note associated with the collateral transaction
      # @!attribute [r] memo
      # @return [String, nil]
      field :memo, :string

      # The chain ID (base-10 number) that the collateral transaction is on
      # @!attribute [r] chain_id
      # @return [Integer, nil] always present in a successful response
      field :chain_id, :integer, api: "chainId"

      # The wallet address the collateral was added from
      # @!attribute [r] wallet_address
      # @return [String, nil] always present in a successful response
      field :wallet_address, :string, api: "walletAddress"

      # The hash of the collateral transaction
      # @!attribute [r] transaction_hash
      # @return [String, nil] always present in a successful response
      field :transaction_hash, :string, api: "transactionHash"

      # The identifier of the company under which the collateral transaction was made
      # @!attribute [r] company_id
      # @return [String, nil]
      field :company_id, :string, api: "companyId"

      # The identifier of the user who provided the collateral
      # @!attribute [r] user_id
      # @return [String, nil]
      field :user_id, :string, api: "userId"

      # The time at which the collateral transaction was posted
      # @!attribute [r] posted_at
      # @return [Time, nil]
      field :posted_at, :time, api: "postedAt"
    end

    # Details of the payment transaction, including amount, currency, and status.
    class Payment < Model
      # The amount of the transaction, in cents
      # @!attribute [r] amount
      # @return [Integer, nil] always present in a successful response
      field :amount, :integer

      # The currency of the transaction
      # @!attribute [r] currency
      # @return [String, nil] always present in a successful response
      field :currency, :string

      # The memo or note associated with the transaction
      # @!attribute [r] memo
      # @return [String, nil]
      field :memo, :string

      # The chain ID (base-10 number) that the payment transaction is on
      # @!attribute [r] chain_id
      # @return [Integer, nil]
      field :chain_id, :integer, api: "chainId"

      # The wallet address from which the payment was made
      # @!attribute [r] wallet_address
      # @return [String, nil]
      field :wallet_address, :string, api: "walletAddress"

      # The hash of the payment transaction
      # @!attribute [r] transaction_hash
      # @return [String, nil]
      field :transaction_hash, :string, api: "transactionHash"

      # The identifier of the company under which the payment transaction was made
      # @!attribute [r] company_id
      # @return [String, nil]
      field :company_id, :string, api: "companyId"

      # The identifier of the user who made the payment
      # @!attribute [r] user_id
      # @return [String, nil]
      field :user_id, :string, api: "userId"

      # The status of the transaction
      # One of: pending, completed
      # @!attribute [r] status
      # @return [String, nil] always present in a successful response
      field :status, :string

      # The time at which the payment transaction was posted
      # @!attribute [r] posted_at
      # @return [String, nil]
      field :posted_at, :string, api: "postedAt"
    end

    # Details of the fee transaction, including amount, description, and status.
    class Fee < Model
      # The amount of the fee, in cents
      # @!attribute [r] amount
      # @return [Integer, nil] always present in a successful response
      field :amount, :integer

      # The description of the fee
      # @!attribute [r] description
      # @return [String, nil]
      field :description, :string

      # The identifier of the company to which the fee was charged
      # @!attribute [r] company_id
      # @return [String, nil]
      field :company_id, :string, api: "companyId"

      # The identifier of the user to whom the fee was charged
      # @!attribute [r] user_id
      # @return [String, nil]
      field :user_id, :string, api: "userId"

      # The time at which the fee was posted
      # @!attribute [r] posted_at
      # @return [Time, nil]
      field :posted_at, :time, api: "postedAt"
    end

    # Which variant this record is, read from `type`.
    VARIANTS = %w[spend collateral payment fee].freeze

    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # Which kind of record this is, and therefore which of the detail fields is populated
    # One of: spend, collateral, payment, fee
    # @!attribute [r] type
    # @return [String, nil] always present in a successful response
    field :type, :string

    # Details specific to a spend transaction, including merchant, amount, and user information.
    # @!attribute [r] spend
    # @return [Redrain::Spend, nil]
    field :spend, Spend

    # Details of the collateral transaction, including amount, currency, and transaction
    # details.
    # @!attribute [r] collateral
    # @return [Redrain::Collateral, nil]
    field :collateral, Collateral

    # Details of the payment transaction, including amount, currency, and status.
    # @!attribute [r] payment
    # @return [Redrain::Payment, nil]
    field :payment, Payment

    # Details of the fee transaction, including amount, description, and status.
    # @!attribute [r] fee
    # @return [Redrain::Fee, nil]
    field :fee, Fee

    # @return [Boolean] true when `type` is "spend"
    def spend? = type == "spend"
    # @return [Boolean] true when `type` is "collateral"
    def collateral? = type == "collateral"
    # @return [Boolean] true when `type` is "payment"
    def payment? = type == "payment"
    # @return [Boolean] true when `type` is "fee"
    def fee? = type == "fee"
  end
end
