# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A IssuingUser record.
  class IssuingUser < IssuingApplication
    # The user's unique identifier
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string

    # The identifier of the company the user belongs to, if applicable
    # @!attribute [r] company_id
    # @return [String, nil]
    field :company_id, :string, api: "companyId"

    # The user's first name
    # @!attribute [r] first_name
    # @return [String, nil] always present in a successful response
    field :first_name, :string, api: "firstName"

    # The user's last name
    # @!attribute [r] last_name
    # @return [String, nil] always present in a successful response
    field :last_name, :string, api: "lastName"

    # The user's email address
    # @!attribute [r] email
    # @return [String, nil] always present in a successful response
    field :email, :string

    # Indicates whether the user account is active
    # @!attribute [r] is_active
    # @return [Boolean, nil] always present in a successful response
    field :is_active, :boolean, api: "isActive"

    # Indicates whether the user has accepted the terms of service
    # @!attribute [r] is_terms_of_service_accepted
    # @return [Boolean, nil] always present in a successful response
    field :is_terms_of_service_accepted, :boolean, api: "isTermsOfServiceAccepted"

    # The user's address
    # @!attribute [r] address
    # @return [Redrain::PhysicalAddress, nil]
    field :address, PhysicalAddress

    # The country code for the user's phone number
    # @!attribute [r] phone_country_code
    # @return [String, nil]
    field :phone_country_code, :string, api: "phoneCountryCode"

    # The user's phone number
    # @!attribute [r] phone_number
    # @return [String, nil]
    field :phone_number, :string, api: "phoneNumber"
  end
end
