# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents the spending limit and frequency for a card.
  class IssuingCardLimit < Model
    # The maximum spending amount in cents
    # @!attribute [r] amount
    # @return [Integer, nil] always present in a successful response
    field :amount, :integer

    # The frequency at which the spending limit resets
    # One of: per24HourPeriod, per7DayPeriod, per30DayPeriod, perYearPeriod, allTime,
    # perAuthorization
    # @!attribute [r] frequency
    # @return [String, nil] always present in a successful response
    field :frequency, :string
  end
end
