# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents the body of a request to create a charge, including the amount and a description
  # of the charge.
  class IssuingChargeCreateChargeBody < Model
    # The amount of the charge, in cents
    # @!attribute [r] amount
    # @return [Integer, nil] always present in a successful response
    field :amount, :integer

    # The description of the charge
    # @!attribute [r] description
    # @return [String, nil] always present in a successful response
    field :description, :string
  end
end
