# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # Represents a physical address with components like street, city, region, postal code, and
  # country.
  class PhysicalAddress < Model
    # The first line of the street address
    # @!attribute [r] line1
    # @return [String, nil] always present in a successful response
    field :line1, :string

    # The second line of the street address (optional)
    # @!attribute [r] line2
    # @return [String, nil]
    field :line2, :string

    # The city of the address
    # @!attribute [r] city
    # @return [String, nil] always present in a successful response
    field :city, :string

    # The region or state of the address
    # @!attribute [r] region
    # @return [String, nil] always present in a successful response
    field :region, :string

    # The postal or zip code of the address
    # @!attribute [r] postal_code
    # @return [String, nil] always present in a successful response
    field :postal_code, :string, api: "postalCode"

    # The 2-letter country code of the address
    # @!attribute [r] country_code
    # @return [String, nil] always present in a successful response
    field :country_code, :string, api: "countryCode"

    # The full name of the country
    # @!attribute [r] country
    # @return [String, nil] always present in a successful response
    field :country, :string
  end
end
