# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # The encrypted pin
  class PinRetrieveResponse < Model
    # The encrypted pin
    class EncryptedPin < Model
      # The initialization vector in base64
      # @!attribute [r] iv
      # @return [String, nil] always present in a successful response
      field :iv, :string

      # The encrypted pin in base64
      # @!attribute [r] data
      # @return [String, nil] always present in a successful response
      field :data, :string
    end

    # The encrypted pin
    # @!attribute [r] encrypted_pin
    # @return [Redrain::EncryptedPin, nil] always present in a successful response
    field :encrypted_pin, EncryptedPin, api: "encryptedPin"
  end
end
