# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A UserRetrieveResponse record.
  class UserRetrieveResponse < IssuingApplication
    # The identifier of the user's application
    # @!attribute [r] id
    # @return [String, nil] always present in a successful response
    field :id, :string
  end
end
