# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # A UserRetrieveBalancesResponse record.
  class UserRetrieveBalancesResponse < Model
    # Credit limit of the user, in cents
    # @!attribute [r] credit_limit
    # @return [Integer, nil] always present in a successful response
    field :credit_limit, :integer, api: "creditLimit"

    # Pending charges of the user, in cents
    # @!attribute [r] pending_charges
    # @return [Integer, nil] always present in a successful response
    field :pending_charges, :integer, api: "pendingCharges"

    # Posted charges of the user, in cents
    # @!attribute [r] posted_charges
    # @return [Integer, nil] always present in a successful response
    field :posted_charges, :integer, api: "postedCharges"

    # Balance due of the user, in cents
    # @!attribute [r] balance_due
    # @return [Integer, nil] always present in a successful response
    field :balance_due, :integer, api: "balanceDue"

    # The amount of money the user can spend, in cents
    # @!attribute [r] spending_power
    # @return [Integer, nil] always present in a successful response
    field :spending_power, :integer, api: "spendingPower"
  end
end
