# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.applications+.
    #
    # Covers 0 endpoints: .
    class ApplicationsResource < Resource
      # Backs +client.applications.company+.
      #
      # Covers 5 endpoints: POST /applications/company, GET /applications/company/:companyId,
      # PATCH /applications/company/:companyId, PUT /applications/company/:companyId/reapply,
      # PUT /applications/company/:companyId/document.
      class CompanyResource < Resource
        # Backs +client.applications.company.ubo+.
        #
        # Covers 2 endpoints: PATCH /applications/company/:companyId/ubo/:uboId, PUT
        # /applications/company/:companyId/ubo/document.
        class UboResource < Resource
          # Backs +client.applications.company.ubo.document+.
          #
          # Covers PUT /applications/company/:companyId/ubo/:uboId/document.
          class DocumentResource < Resource
            # Upload a UBO's document to support a company's corporate application
            #
            # Uploads a document for a company's Ultimate Beneficial Owner (UBO) to support the
            # company's corporate application. This endpoint allows for the submission of
            # various legal and identification documents.
            #
            # PUT /applications/company/:companyId/ubo/:uboId/document
            #
            # @param [String] ubo_id the resource id
            # @param [String] company_id The identifier of the company to upload a document for
            # @param [String] type The type of the document being uploaded. one of: idCard,
            #   passport, drivers, residencePermit, utilityBill, selfie, videoSelfie,
            #   profileImage, idDocPhoto, agreement, contract, driversTranslation, investorDoc,
            #   vehicleRegistrationCertificate, incomeSource, paymentMethod, bankCard,
            #   covidVaccinationForm, other. optional
            # @param [String] side The side of the document being uploaded. one of: front, back.
            #   optional
            # @param [String] country The country where the document was issued. optional
            # @param [Redrain::Upload, File, String] document The actual document file to be
            #   uploaded. The document must be in binary format, and the maximum allowed size is
            #   20 MB
            # @return [nil] this endpoint returns no content
            def upload(ubo_id, company_id:, document:, type: nil, side: nil, country: nil)
              body = {
                "type" => type,
                "side" => side,
                "country" => country
              }
              files = {
                "document" => document
              }

              request(
                :put,
                path("/applications/company/{companyId}/ubo/{uboId}/document", companyId: company_id, uboId: ubo_id),
                body: body,
                files: files
              )
            end
          end

          sub_resource :document, DocumentResource

          # Update a company UBO's application
          #
          # Updates the application information for a company's Ultimate Beneficial Owner (UBO).
          # This allows modification of the UBO's personal details such as name, birth date,
          # national ID, and address.
          #
          # PATCH /applications/company/:companyId/ubo/:uboId
          #
          # @param [String] ubo_id the resource id
          # @param [String] company_id The identifier of the company whose UBO's application is
          #   being updated
          # @param [String] first_name The UBO's first name. optional
          # @param [String] last_name The UBO's last name. optional
          # @param [String] birth_date The UBO's birth date. optional
          # @param [String] national_id The UBO's national ID number. For the US, this is a
          #   9-digit SSN. optional
          # @param [String] country_of_issue The 2-digit country code of the user's national ID
          #   issuer. optional
          # @param [String] email The UBO's email address. optional
          # @param [Hash] address Represents a physical address with components like street,
          #   city, region, postal code, and country. optional
          # @return [Redrain::IssuingCompany]
          def update(
            ubo_id,
            company_id:,
            first_name: nil,
            last_name: nil,
            birth_date: nil,
            national_id: nil,
            country_of_issue: nil,
            email: nil,
            address: nil
          )
            body = {
              "firstName" => first_name,
              "lastName" => last_name,
              "birthDate" => birth_date,
              "nationalId" => national_id,
              "countryOfIssue" => country_of_issue,
              "email" => email,
              "address" => address
            }

            request(
              :patch,
              path("/applications/company/{companyId}/ubo/{uboId}", companyId: company_id, uboId: ubo_id),
              body: body,
              into: IssuingCompany
            )
          end

          # [Deprecated] Upload a UBO's document to support a company's corporate application
          #
          # This deprecated endpoint allows the upload of a document for a UBO to support a
          # company's corporate application. It is recommended to use the newer endpoint for
          # document uploads.
          #
          # PUT /applications/company/:companyId/ubo/document
          #
          # @param [String] company_id the resource id
          # @param [String] email The UBO's email address
          # @param [String] type The type of the document being uploaded. one of: idCard,
          #   passport, drivers, residencePermit, utilityBill, selfie, videoSelfie, profileImage,
          #   idDocPhoto, agreement, contract, driversTranslation, investorDoc,
          #   vehicleRegistrationCertificate, incomeSource, paymentMethod, bankCard,
          #   covidVaccinationForm, other. optional
          # @param [String] side The side of the document being uploaded. one of: front, back.
          #   optional
          # @param [String] country The country where the document was issued. optional
          # @param [Redrain::Upload, File, String] document The actual document file to be
          #   uploaded. The document must be in binary format, and the maximum allowed size is 20
          #   MB
          # @return [nil] this endpoint returns no content
          def upload_document(company_id, email:, document:, type: nil, side: nil, country: nil)
            body = {
              "email" => email,
              "type" => type,
              "side" => side,
              "country" => country
            }
            files = {
              "document" => document
            }

            request(
              :put,
              path("/applications/company/{companyId}/ubo/document", companyId: company_id),
              body: body,
              files: files
            )
          end
        end

        sub_resource :ubo, UboResource

        # Create a corporate account application
        #
        # Submits an application to create a corporate account. The application requires details
        # about the company, its legal entity, representatives, and beneficial owners. The
        # initial user must provide a wallet address.
        #
        # POST /applications/company
        #
        # @param [Hash] initial_user
        # @param [String] name The name of the company requesting to create an account
        # @param [Hash] address Represents a physical address with components like street, city,
        #   region, postal code, and country
        # @param [String] chain_id The chain ID of the external collateral contract, if used.
        #   Not required when using Rain's collateral contracts. optional
        # @param [String] contract_address The address of the external collateral contract, if
        #   used. Not required when using Rain's collateral contracts. optional
        # @param [String] source_key A unique identifier for the origin of the user. optional
        # @param [Hash] entity The company's legal entity details
        # @param [Array<Hash>] representatives The company's representatives
        # @param [Array<Hash>] ultimate_beneficial_owners The company's ultimate beneficial
        #   owners (UBOs)
        # @return [Redrain::IssuingCompany]
        def create(
          initial_user:,
          name:,
          address:,
          entity:,
          representatives:,
          ultimate_beneficial_owners:,
          chain_id: nil,
          contract_address: nil,
          source_key: nil
        )
          body = {
            "initialUser" => initial_user,
            "name" => name,
            "address" => address,
            "chainId" => chain_id,
            "contractAddress" => contract_address,
            "sourceKey" => source_key,
            "entity" => entity,
            "representatives" => representatives,
            "ultimateBeneficialOwners" => ultimate_beneficial_owners
          }

          request(:post, "/applications/company", body: body, into: IssuingCompany)
        end

        # Get the status of a company's corporate application
        #
        # Retrieves the current status and details of a company's corporate application,
        # including the company's ultimate beneficial owners and application progress.
        #
        # GET /applications/company/:companyId
        #
        # @param [String] company_id the resource id
        # @return [Redrain::CompanyRetrieveResponse]
        def retrieve(company_id)
          request(
            :get,
            path("/applications/company/{companyId}", companyId: company_id),
            into: CompanyRetrieveResponse
          )
        end

        # Update a company's corporate application
        #
        # Updates the information for an existing corporate account application. The company's
        # details, including name, address, and legal entity information, can be modified
        # through this endpoint.
        #
        # PATCH /applications/company/:companyId
        #
        # @param [String] company_id the resource id
        # @param [String] name The name of the company for the corporate application. optional
        # @param [Hash] address Represents a physical address with components like street, city,
        #   region, postal code, and country. optional
        # @param [Hash] entity The company's legal entity details. optional
        # @return [Redrain::IssuingCompany]
        def update(company_id, name: nil, address: nil, entity: nil)
          body = {
            "name" => name,
            "address" => address,
            "entity" => entity
          }

          request(
            :patch,
            path("/applications/company/{companyId}", companyId: company_id),
            body: body,
            into: IssuingCompany
          )
        end

        # Reapply or respond to a request for information for a company's corporate application
        #
        # Allows a company to reapply or respond to a request for information after submitting
        # their corporate application. This endpoint is typically used when additional
        # information or corrections are needed.
        #
        # PUT /applications/company/:companyId/reapply
        #
        # @param [String] company_id the resource id
        # @param [Hash] initial_user The initial user of the company who will be the owner on
        #   the Rain smart contract. This user must provide various personal details
        # @param [String] name The name of the company reapplying for the corporate application
        # @param [Hash] address Represents a physical address with components like street, city,
        #   region, postal code, and country
        # @param [Hash] entity The company's legal entity details
        # @param [Array<Hash>] representatives The company's representatives
        # @param [Array<Hash>] ultimate_beneficial_owners The company's ultimate beneficial
        #   owners (UBOs)
        # @return [Redrain::IssuingCompany]
        def reapply(
          company_id,
          initial_user:,
          name:,
          address:,
          entity:,
          representatives:,
          ultimate_beneficial_owners:
        )
          body = {
            "initialUser" => initial_user,
            "name" => name,
            "address" => address,
            "entity" => entity,
            "representatives" => representatives,
            "ultimateBeneficialOwners" => ultimate_beneficial_owners
          }

          request(
            :put,
            path("/applications/company/{companyId}/reapply", companyId: company_id),
            body: body,
            into: IssuingCompany
          )
        end

        # Upload a document to support a company's corporate application
        #
        # Uploads a document that supports a company's corporate application. This is typically
        # used to provide additional documentation, such as proof of address, incorporation
        # certificates, or other required legal documents.
        #
        # PUT /applications/company/:companyId/document
        #
        # @param [String] company_id the resource id
        # @param [String] name The name of the document being uploaded. optional
        # @param [String] type The type of the document being uploaded. one of:
        #   directorsRegistry, stateRegistry, incumbencyCert, proofOfAddress, trustAgreement,
        #   informationStatement, incorporationCert, incorporationArticles, shareholderRegistry,
        #   goodStandingCert, powerOfAttorney, other. optional
        # @param [String] side The side of the document being uploaded. one of: front, back.
        #   optional
        # @param [String] country The country where the document was issued. optional
        # @param [Redrain::Upload, File, String] document The actual document file to be
        #   uploaded. The document must be in binary format, and the maximum allowed size is 20 MB
        # @return [nil] this endpoint returns no content
        def upload_document(
          company_id,
          document:,
          name: nil,
          type: nil,
          side: nil,
          country: nil
        )
          body = {
            "name" => name,
            "type" => type,
            "side" => side,
            "country" => country
          }
          files = {
            "document" => document
          }

          request(
            :put,
            path("/applications/company/{companyId}/document", companyId: company_id),
            body: body,
            files: files
          )
        end
      end

      # Backs +client.applications.user+.
      #
      # Covers 6 endpoints: POST /applications/user, GET /applications/user/:userId, PATCH
      # /applications/user/:userId, POST /applications/user/initiate, PUT
      # /applications/user/:userId/reapply, PUT /applications/user/:userId/document.
      class UserResource < Resource
        # Create a consumer application for a user
        #
        # Submits an application to create a consumer account for a user. The application can be
        # submitted using a Sumsub share token, Persona share token, or directly via API. The
        # user must provide details about their wallet, occupation, salary, and other
        # account-related information.
        #
        # POST /applications/user
        #
        # @param [String] wallet_address The user's Ethereum Virtual Machine (EVM) address.
        #   Either walletAddress or solanaAddress is required if using a Rain-managed solution,
        #   but optional otherwise. optional
        # @param [String] solana_address The user's Solana address. Either walletAddress or
        #   solanaAddress is required if using a Rain-managed solution, but optional otherwise.
        #   optional
        # @param [String] chain_id The chain ID of the user's external collateral contract, if
        #   applicable. Not required when using Rain's collateral contracts. optional
        # @param [String] contract_address The address of the user's external collateral
        #   contract, if applicable. Not required when using Rain's collateral contracts. optional
        # @param [String] source_key A unique identifier for the source of this user. optional
        # @param [String] ip_address This user's IP address
        # @param [String] occupation The user's occupation
        # @param [String] annual_salary The user's annual salary
        # @param [String] account_purpose The purpose of the user's account
        # @param [String] expected_monthly_volume The estimated monthly spending amount for the
        #   user
        # @param [Boolean] is_terms_of_service_accepted Indicates whether the user has accepted
        #   the terms of service. one of: true
        # @param [Boolean] has_existing_documents Indicates whether the user will use existing
        #   documents for additional verification. optional
        # @return [Redrain::IssuingUser]
        def create(
          ip_address:,
          occupation:,
          annual_salary:,
          account_purpose:,
          expected_monthly_volume:,
          is_terms_of_service_accepted:,
          wallet_address: nil,
          solana_address: nil,
          chain_id: nil,
          contract_address: nil,
          source_key: nil,
          has_existing_documents: nil
        )
          body = {
            "walletAddress" => wallet_address,
            "solanaAddress" => solana_address,
            "chainId" => chain_id,
            "contractAddress" => contract_address,
            "sourceKey" => source_key,
            "ipAddress" => ip_address,
            "occupation" => occupation,
            "annualSalary" => annual_salary,
            "accountPurpose" => account_purpose,
            "expectedMonthlyVolume" => expected_monthly_volume,
            "isTermsOfServiceAccepted" => is_terms_of_service_accepted,
            "hasExistingDocuments" => has_existing_documents
          }

          request(:post, "/applications/user", body: body, into: IssuingUser)
        end

        # Get the status of a user's consumer application
        #
        # Retrieves the current status and details of a user's consumer application. This
        # includes the user's application progress and related information.
        #
        # GET /applications/user/:userId
        #
        # @param [String] user_id the resource id
        # @return [Redrain::UserRetrieveResponse]
        def retrieve(user_id)
          request(
            :get,
            path("/applications/user/{userId}", userId: user_id),
            into: UserRetrieveResponse
          )
        end

        # Update a user's consumer application
        #
        # Updates the application information for a user, including personal details such as
        # name, birth date, occupation, national ID, and account purpose.
        #
        # PATCH /applications/user/:userId
        #
        # @param [String] user_id the resource id
        # @param [String] first_name The user's first name. optional
        # @param [String] last_name The user's last name. optional
        # @param [String] birth_date The user's birth date. optional
        # @param [String] national_id The user's national ID number. For the US, this is a
        #   9-digit SSN. optional
        # @param [String] country_of_issue The 2-digit country code of the user's national ID
        #   issuer. optional
        # @param [Hash] address Represents a physical address with components like street, city,
        #   region, postal code, and country. optional
        # @param [String] ip_address The user's IP address. optional
        # @param [String] occupation The user's occupation. optional
        # @param [String] annual_salary The user's annual salary. optional
        # @param [String] account_purpose The purpose of the user's account. optional
        # @param [String] expected_monthly_volume The estimated monthly spending amount for the
        #   user. optional
        # @param [Boolean] is_terms_of_service_accepted Indicates whether the user has accepted
        #   the terms of service. one of: true. optional
        # @param [Boolean] has_existing_documents Indicates whether the user will use existing
        #   documents for additional verification. optional
        # @return [Redrain::IssuingUser]
        def update(
          user_id,
          first_name: nil,
          last_name: nil,
          birth_date: nil,
          national_id: nil,
          country_of_issue: nil,
          address: nil,
          ip_address: nil,
          occupation: nil,
          annual_salary: nil,
          account_purpose: nil,
          expected_monthly_volume: nil,
          is_terms_of_service_accepted: nil,
          has_existing_documents: nil
        )
          body = {
            "firstName" => first_name,
            "lastName" => last_name,
            "birthDate" => birth_date,
            "nationalId" => national_id,
            "countryOfIssue" => country_of_issue,
            "address" => address,
            "ipAddress" => ip_address,
            "occupation" => occupation,
            "annualSalary" => annual_salary,
            "accountPurpose" => account_purpose,
            "expectedMonthlyVolume" => expected_monthly_volume,
            "isTermsOfServiceAccepted" => is_terms_of_service_accepted,
            "hasExistingDocuments" => has_existing_documents
          }

          request(
            :patch,
            path("/applications/user/{userId}", userId: user_id),
            body: body,
            into: IssuingUser
          )
        end

        # Initiate a consumer application for a user
        #
        # Submits an initial application for creating a consumer account. This request gathers
        # basic personal details of the user, including their first and last name, email
        # address, and optional wallet address if using a Rain-managed solution or hosted
        # completion flow.
        #
        # POST /applications/user/initiate
        #
        # @param [String] first_name The user's first name. optional
        # @param [String] last_name The user's last name. optional
        # @param [String] email The user's email address. optional
        # @param [String] wallet_address The user's wallet address. Required if using the hosted
        #   completion flow and a Rain-managed solution. Not required otherwise. optional
        # @return [Redrain::IssuingUser]
        def initiate(first_name: nil, last_name: nil, email: nil, wallet_address: nil)
          body = {
            "firstName" => first_name,
            "lastName" => last_name,
            "email" => email,
            "walletAddress" => wallet_address
          }

          request(:post, "/applications/user/initiate", body: body, into: IssuingUser)
        end

        # Reapply or respond to a request for information for a user's consumer application
        #
        # Allows a user to reapply or respond to a request for additional information regarding
        # their consumer application. This is used when the initial application needs updating
        # or more information is required.
        #
        # PUT /applications/user/:userId/reapply
        #
        # @param [String] user_id the resource id
        # @param [String] birth_date The user's birth date
        # @param [String] national_id The user's national ID number. For the US, this is a
        #   9-digit SSN
        # @param [String] country_of_issue The 2-digit country code of the user's national ID
        #   issuer
        # @param [Hash] address Represents a physical address with components like street, city,
        #   region, postal code, and country
        # @param [String] ip_address The user's IP address
        # @param [String] occupation The user's occupation
        # @param [String] annual_salary The user's annual salary
        # @param [String] account_purpose The purpose of the user's account
        # @param [String] expected_monthly_volume The estimated monthly spending amount for the
        #   user
        # @param [Boolean] is_terms_of_service_accepted Indicates whether the user has accepted
        #   the terms of service. one of: true
        # @param [Boolean] has_existing_documents Indicates whether the user will use existing
        #   documents for additional verification. optional
        # @return [Redrain::IssuingUser]
        def reapply(
          user_id,
          birth_date:,
          national_id:,
          country_of_issue:,
          address:,
          ip_address:,
          occupation:,
          annual_salary:,
          account_purpose:,
          expected_monthly_volume:,
          is_terms_of_service_accepted:,
          has_existing_documents: nil
        )
          body = {
            "birthDate" => birth_date,
            "nationalId" => national_id,
            "countryOfIssue" => country_of_issue,
            "address" => address,
            "ipAddress" => ip_address,
            "occupation" => occupation,
            "annualSalary" => annual_salary,
            "accountPurpose" => account_purpose,
            "expectedMonthlyVolume" => expected_monthly_volume,
            "isTermsOfServiceAccepted" => is_terms_of_service_accepted,
            "hasExistingDocuments" => has_existing_documents
          }

          request(
            :put,
            path("/applications/user/{userId}/reapply", userId: user_id),
            body: body,
            into: IssuingUser
          )
        end

        # Upload a document to support a user's consumer application
        #
        # Uploads a document for a user to support their consumer application. This is used to
        # provide additional verification documents such as IDs, utility bills, and other
        # required legal documents.
        #
        # PUT /applications/user/:userId/document
        #
        # @param [String] user_id the resource id
        # @param [String] name The name or title of the document being uploaded. optional
        # @param [String] type The type of the document being uploaded. one of: idCard,
        #   passport, drivers, residencePermit, utilityBill, selfie, videoSelfie, profileImage,
        #   idDocPhoto, agreement, contract, driversTranslation, investorDoc,
        #   vehicleRegistrationCertificate, incomeSource, paymentMethod, bankCard,
        #   covidVaccinationForm, other. optional
        # @param [String] side The side of the document being uploaded. one of: front, back.
        #   optional
        # @param [String] country The country where the document was issued. optional
        # @param [Redrain::Upload, File, String] document The actual document file to be
        #   uploaded. The document must be in binary format, and the maximum allowed size is 20 MB
        # @return [nil] this endpoint returns no content
        def upload_document(user_id, document:, name: nil, type: nil, side: nil, country: nil)
          body = {
            "name" => name,
            "type" => type,
            "side" => side,
            "country" => country
          }
          files = {
            "document" => document
          }

          request(
            :put,
            path("/applications/user/{userId}/document", userId: user_id),
            body: body,
            files: files
          )
        end
      end

      sub_resource :company, CompanyResource
      sub_resource :user, UserResource

    end
  end
end
