# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.balances+.
    #
    # Covers GET /balances.
    class BalancesResource < Resource
      # Get an authorized user tenant's credit balances
      #
      # Retrieves the credit balances for an authorized user tenant. This includes details such
      # as credit limit, pending charges, posted charges, balance due, and spending power.
      #
      # GET /balances
      # @return [Redrain::BalanceRetrieveResponse]
      def retrieve
        request(:get, "/balances", into: BalanceRetrieveResponse)
      end
    end
  end
end
