# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.cards+.
    #
    # Covers 4 endpoints: GET /cards/:cardId, PATCH /cards/:cardId, GET /cards, GET
    # /cards/:cardId/secrets.
    class CardsResource < Resource
      # Backs +client.cards.pin+.
      #
      # Covers 2 endpoints: GET /cards/:cardId/pin, PUT /cards/:cardId/pin.
      class PinResource < Resource
        # Get a card's PIN
        #
        # Retrieve the encrypted PIN for a specific card
        #
        # GET /cards/:cardId/pin
        #
        # @param [String] card_id the resource id
        # @return [Redrain::PinRetrieveResponse]
        def retrieve(card_id)
          request(:get, path("/cards/{cardId}/pin", cardId: card_id), into: PinRetrieveResponse)
        end

        # Update a card's PIN.
        #
        # Updates the PIN of a specific card by setting the encrypted PIN
        #
        # PUT /cards/:cardId/pin
        #
        # @param [String] card_id the resource id
        # @param [Hash] encrypted_pin The encrypted pin
        # @return [nil] this endpoint returns no content
        def update(card_id, encrypted_pin:)
          body = {
            "encryptedPin" => encrypted_pin
          }

          request(:put, path("/cards/{cardId}/pin", cardId: card_id), body: body)
        end
      end

      include Redrain::Page
      sub_resource :pin, PinResource

      # Get a card by its id
      #
      # Retrieve detailed information for a specific card by its unique ID
      #
      # GET /cards/:cardId
      #
      # @param [String] card_id the resource id
      # @return [Redrain::IssuingCard]
      def retrieve(card_id)
        request(:get, path("/cards/{cardId}", cardId: card_id), into: IssuingCard)
      end

      # Update a card
      #
      # Update details for an existing card, such as status, limit, billing address, and
      # configuration.
      #
      # PATCH /cards/:cardId
      #
      # @param [String] card_id the resource id
      # @param [String] status The current status of the card. one of: notActivated, active,
      #   locked, canceled. optional
      # @param [Hash] limit Represents the spending limit and frequency for a card. optional
      # @param [Hash] billing Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @param [Hash] configuration Configuration for the card, such as virtual card art.
      #   optional
      # @return [Redrain::IssuingCard]
      def update(card_id, status: nil, limit: nil, billing: nil, configuration: nil)
        body = {
          "status" => status,
          "limit" => limit,
          "billing" => billing,
          "configuration" => configuration
        }

        request(:patch, path("/cards/{cardId}", cardId: card_id), body: body, into: IssuingCard)
      end

      # Get all the cards for a user or company
      #
      # Retrieves all cards associated with a user or company. You can filter by user or company
      # ID and card status.
      #
      # GET /cards
      #
      # @param [String] company_id For corporate cards, the identifier of the company to get
      #   cards for. optional
      # @param [String] user_id The identifier of the user to get cards for. optional
      # @param [String] status Filter cards by status. one of: notActivated, active, locked,
      #   canceled. optional
      # @param [String] cursor The ID of the resource after which to start fetching. optional
      # @param [Integer] limit The number of resources to fetch. optional
      # @return [Array<Redrain::IssuingCard>]
      def list(company_id: nil, user_id: nil, status: nil, cursor: nil, limit: nil)
        query = {
          "companyId" => company_id,
          "userId" => user_id,
          "status" => status,
          "cursor" => cursor,
          "limit" => limit
        }

        request(:get, "/cards", query: query, into: [IssuingCard])
      end

      # Get a card's encrypted data
      #
      # Retrieve the encrypted data for a specific card, including the encrypted PAN and CVC
      #
      # GET /cards/:cardId/secrets
      #
      # @param [String] card_id the resource id
      # @return [Redrain::CardRetrieveSecretsResponse]
      def retrieve_secrets(card_id)
        request(
          :get,
          path("/cards/{cardId}/secrets", cardId: card_id),
          into: CardRetrieveSecretsResponse
        )
      end
    end
  end
end
