# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.companies+.
    #
    # Covers 8 endpoints: GET /companies/:companyId, PATCH /companies/:companyId, GET
    # /companies, POST /companies/:companyId/charges, POST /companies/:companyId/users, POST
    # /companies/:companyId/payments, GET /companies/:companyId/balances, GET
    # /companies/:companyId/contracts.
    class CompaniesResource < Resource
      # Backs +client.companies.signatures+.
      #
      # Covers 2 endpoints: GET /companies/:companyId/signatures/payments, GET
      # /companies/:companyId/signatures/withdrawals.
      class SignaturesResource < Resource
        # Get payment signature for a company
        #
        # Retrieve the payment signature for a company, which is required for completing payment
        # transactions.
        #
        # GET /companies/:companyId/signatures/payments
        #
        # @param [String] company_id the resource id
        # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
        #   deployed on. optional
        # @param [String] token The address of the token that the payment should be made in (as
        #   a hex string for EVM or base58 string for Solana)
        # @param [String] amount The amount of tokens that are being paid
        # @param [String] admin_address The address of the admin making the payment, as a hex
        #   string for EVM or base58 string for Solana
        # @param [Boolean] is_amount_native Indicates whether the amount is in the asset's
        #   native units. If false, the amount is expressed in cents. optional
        # @return [Redrain::IssuingSignature]
        def retrieve_payment_signature(
          company_id,
          token:,
          amount:,
          admin_address:,
          chain_id: nil,
          is_amount_native: nil
        )
          query = {
            "chainId" => chain_id,
            "token" => token,
            "amount" => amount,
            "adminAddress" => admin_address,
            "isAmountNative" => is_amount_native
          }

          request(
            :get,
            path("/companies/{companyId}/signatures/payments", companyId: company_id),
            query: query,
            into: IssuingSignature
          )
        end

        # Get withdrawal signature for a company
        #
        # Retrieve the withdrawal signature for a company, which is required for processing
        # withdrawal requests.
        #
        # GET /companies/:companyId/signatures/withdrawals
        #
        # @param [String] company_id the resource id
        # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
        #   deployed on. optional
        # @param [String] token The address of the token that the withdrawal should be made in,
        #   as a hex string for EVM or base58 string for Solana
        # @param [String] amount The amount of tokens being withdrawn
        # @param [String] admin_address The address of the admin making the payment, as a hex
        #   string for EVM or base58 string for Solana
        # @param [String] recipient_address The address the withdrawal should be sent to, as a
        #   hex string for EVM or base58 string for Solana
        # @param [Boolean] is_amount_native Indicates whether the amount is in the asset's
        #   native units. If false, the amount is expressed in cents. optional
        # @return [Redrain::IssuingSignature]
        def retrieve_withdrawal_signature(
          company_id,
          token:,
          amount:,
          admin_address:,
          recipient_address:,
          chain_id: nil,
          is_amount_native: nil
        )
          query = {
            "chainId" => chain_id,
            "token" => token,
            "amount" => amount,
            "adminAddress" => admin_address,
            "recipientAddress" => recipient_address,
            "isAmountNative" => is_amount_native
          }

          request(
            :get,
            path("/companies/{companyId}/signatures/withdrawals", companyId: company_id),
            query: query,
            into: IssuingSignature
          )
        end
      end

      include Redrain::Page
      sub_resource :signatures, SignaturesResource

      # Get a company by ID
      #
      # Retrieve detailed information about a specific company using its unique ID
      #
      # GET /companies/:companyId
      #
      # @param [String] company_id the resource id
      # @return [Redrain::IssuingCompany]
      def retrieve(company_id)
        request(
          :get,
          path("/companies/{companyId}", companyId: company_id),
          into: IssuingCompany
        )
      end

      # Update a company
      #
      # Update the details of an existing company such as its name and address
      #
      # PATCH /companies/:companyId
      #
      # @param [String] company_id the resource id
      # @param [String] name The company's name on the Rain platform. optional
      # @param [Hash] address Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @return [Redrain::IssuingCompany]
      def update(company_id, name: nil, address: nil)
        body = {
          "name" => name,
          "address" => address
        }

        request(
          :patch,
          path("/companies/{companyId}", companyId: company_id),
          body: body,
          into: IssuingCompany
        )
      end

      # Get all companies
      #
      # Retrieves a list of all companies registered in the system
      #
      # GET /companies
      #
      # @param [String] cursor The ID of the resource after which to start fetching. optional
      # @param [Integer] limit The number of resources to fetch. optional
      # @return [Array<Redrain::IssuingCompany>]
      def list(cursor: nil, limit: nil)
        query = {
          "cursor" => cursor,
          "limit" => limit
        }

        request(:get, "/companies", query: query, into: [IssuingCompany])
      end

      # Charge a company a custom fee
      #
      # Initiate a custom fee charge for a company.
      #
      # POST /companies/:companyId/charges
      #
      # @param [String] company_id the resource id
      # @param [Integer] amount The amount of the charge, in cents
      # @param [String] description The description of the charge
      # @return [Redrain::IssuingChargeCreateChargeResponse]
      def charge(company_id, amount:, description:)
        body = {
          "amount" => amount,
          "description" => description
        }

        request(
          :post,
          path("/companies/{companyId}/charges", companyId: company_id),
          body: body,
          into: IssuingChargeCreateChargeResponse
        )
      end

      # Create a user in a company
      #
      # Creates a new user within a specific company. The user must provide details such as
      # their name, birthdate, and contact information.
      #
      # POST /companies/:companyId/users
      #
      # @param [String] company_id the resource id
      # @param [String] first_name The user's first name
      # @param [String] last_name The user's last name
      # @param [String] birth_date The user's birth date. optional
      # @param [String] email The user's email address
      # @param [String] wallet_address The user's wallet address. optional
      # @param [Hash] address Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @param [String] phone_country_code The user's phone country code. optional
      # @param [String] phone_number The user's phone number. optional
      # @param [Boolean] is_terms_of_service_accepted Indicates whether the user has accepted
      #   the terms of service
      # @return [Redrain::IssuingUser]
      def create_user(
        company_id,
        first_name:,
        last_name:,
        email:,
        is_terms_of_service_accepted:,
        birth_date: nil,
        wallet_address: nil,
        address: nil,
        phone_country_code: nil,
        phone_number: nil
      )
        body = {
          "firstName" => first_name,
          "lastName" => last_name,
          "birthDate" => birth_date,
          "email" => email,
          "walletAddress" => wallet_address,
          "address" => address,
          "phoneCountryCode" => phone_country_code,
          "phoneNumber" => phone_number,
          "isTermsOfServiceAccepted" => is_terms_of_service_accepted
        }

        request(
          :post,
          path("/companies/{companyId}/users", companyId: company_id),
          body: body,
          into: IssuingUser
        )
      end

      # Initiate a payment for a company
      #
      # Initiate a payment for a specific company by providing the payment amount and wallet
      # address.
      #
      # POST /companies/:companyId/payments
      #
      # @param [String] company_id the resource id
      # @param [Integer] amount The amount of the payment, in cents
      # @param [Integer] chain_id The chain ID (base-10 number) that the payment transaction is
      #   on. optional
      # @param [String] wallet_address The wallet address the payment is being sent from
      # @return [Redrain::CompanyInitiatePaymentResponse]
      def initiate_payment(company_id, amount:, wallet_address:, chain_id: nil)
        body = {
          "amount" => amount,
          "chainId" => chain_id,
          "walletAddress" => wallet_address
        }

        request(
          :post,
          path("/companies/{companyId}/payments", companyId: company_id),
          body: body,
          into: CompanyInitiatePaymentResponse
        )
      end

      # Get a company's credit balances
      #
      # Retrieve the current credit balances of a company, including credit limits, pending
      # charges, and the amount due.
      #
      # GET /companies/:companyId/balances
      #
      # @param [String] company_id the resource id
      # @return [Redrain::CompanyRetrieveBalancesResponse]
      def retrieve_balances(company_id)
        request(
          :get,
          path("/companies/{companyId}/balances", companyId: company_id),
          into: CompanyRetrieveBalancesResponse
        )
      end

      # Get smart contract information for a company
      #
      # Retrieve the smart contract details associated with a company
      #
      # GET /companies/:companyId/contracts
      #
      # @param [String] company_id the resource id
      # @return [Array<Redrain::IssuingContract>]
      def retrieve_contracts(company_id)
        request(
          :get,
          path("/companies/{companyId}/contracts", companyId: company_id),
          into: [IssuingContract]
        )
      end
    end
  end
end
