# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.contracts+.
    #
    # Covers GET /contracts.
    class ContractsResource < Resource
      # Get smart contract information for an authorized user tenant
      #
      # Retrieve the smart contract information for a specific authorized user tenant.
      #
      # GET /contracts
      # @return [Array<Redrain::IssuingContract>]
      def list
        request(:get, "/contracts", into: [IssuingContract])
      end
    end
  end
end
