# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.disputes+.
    #
    # Covers 3 endpoints: GET /disputes/:disputeId, PATCH /disputes/:disputeId, GET /disputes.
    class Disputes < Resource
      # Backs +client.disputes.evidence+.
      #
      # Covers 2 endpoints: GET /disputes/:disputeId/evidence, PUT
      # /disputes/:disputeId/evidence.
      class Evidence < Resource
        # Get a dispute's file evidence
        #
        # Retrieve the file evidence associated with a dispute.
        #
        # GET /disputes/:disputeId/evidence
        #
        # @param [String] dispute_id the resource id
        # @return [String] the raw bytes of the response
        def list(dispute_id)
          request(
            :get,
            path("/disputes/{disputeId}/evidence", disputeId: dispute_id),
            binary: true
          )
        end

        # Upload a file as evidence for a dispute
        #
        # Upload a file that will serve as evidence for a dispute.
        #
        # PUT /disputes/:disputeId/evidence
        #
        # @param [String] dispute_id the resource id
        # @param [String] name The name of the evidence
        # @param [String] type The type of evidence
        # @param [Redrain::Upload, File, String] evidence The evidence to upload
        # @return [nil] this endpoint returns no content
        def upload(dispute_id, name:, type:, evidence:)
          body = {
            "name" => name,
            "type" => type
          }
          files = {
            "evidence" => evidence
          }

          request(
            :put,
            path("/disputes/{disputeId}/evidence", disputeId: dispute_id),
            body: body,
            files: files
          )
        end
      end

      include Redrain::Page
      sub_resource :evidence, Evidence

      # Get a dispute by its ID
      #
      # Retrieve details of a specific dispute using its unique ID.
      #
      # GET /disputes/:disputeId
      #
      # @param [String] dispute_id the resource id
      # @return [Redrain::IssuingDispute]
      def retrieve(dispute_id)
        request(
          :get,
          path("/disputes/{disputeId}", disputeId: dispute_id),
          into: IssuingDispute
        )
      end

      # Update a dispute
      #
      # Update the status or evidence of a dispute, typically to mark it as canceled or add new
      # evidence.
      #
      # PATCH /disputes/:disputeId
      #
      # @param [String] dispute_id the resource id
      # @param [String] status The new status of the dispute. Can only be set to 'canceled'. one
      #   of: canceled. optional
      # @param [String] text_evidence The textual evidence to add to the dispute. optional
      # @return [nil] this endpoint returns no content
      def update(dispute_id, status: nil, text_evidence: nil)
        body = {
          "status" => status,
          "textEvidence" => text_evidence
        }

        request(:patch, path("/disputes/{disputeId}", disputeId: dispute_id), body: body)
      end

      # Get all disputes
      #
      # Retrieve all disputes, optionally filtered by company, user, or transaction ID.
      #
      # GET /disputes
      #
      # @param [String] company_id For corporate cards, the identifier of the company to get
      #   disputes for. optional
      # @param [String] user_id The ID of the user to get disputes for. optional
      # @param [String] transaction_id The ID of the transaction to get disputes for. optional
      # @param [String] cursor The ID of the resource after which to start fetching. optional
      # @param [Integer] limit The number of resources to fetch. optional
      # @return [Array<Redrain::IssuingDispute>]
      def list(company_id: nil, user_id: nil, transaction_id: nil, cursor: nil, limit: nil)
        query = {
          "companyId" => company_id,
          "userId" => user_id,
          "transactionId" => transaction_id,
          "cursor" => cursor,
          "limit" => limit
        }

        request(:get, "/disputes", query: query, into: [IssuingDispute])
      end
    end
  end
end
