# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.keys+.
    #
    # Covers 2 endpoints: POST /keys, DELETE /keys/:keyId.
    class KeysResource < Resource
      # Create a key
      #
      # This endpoint allows for the creation of a new key with a specified name and expiration
      # time. The key is used for various security operations within the system.
      #
      # POST /keys
      #
      # @param [String] name The name of the key being created
      # @param [String] expires_at The expiration timestamp of the key
      # @return [Redrain::IssuingKey]
      def create(name:, expires_at:)
        body = {
          "name" => name,
          "expiresAt" => expires_at
        }

        request(:post, "/keys", body: body, into: IssuingKey)
      end

      # Delete a key
      #
      # This endpoint allows for the deletion of a specific key using its unique ID.
      #
      # DELETE /keys/:keyId
      #
      # @param [String] key_id the resource id
      # @return [nil] this endpoint returns no content
      def delete(key_id)
        request(:delete, path("/keys/{keyId}", keyId: key_id))
      end
    end
  end
end
