# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.payments+.
    #
    # Covers POST /payments.
    class PaymentsResource < Resource
      # Initiate a payment for an authorized user tenant
      #
      # This endpoint initiates a payment for an authorized user tenant. The request includes
      # the amount to be transferred and the wallet address to send the payment from.
      #
      # POST /payments
      #
      # @param [Integer] amount The amount of the payment, in cents
      # @param [Integer] chain_id The chain ID (base-10 number) that the payment transaction is
      #   on. optional
      # @param [String] wallet_address The wallet address the payment is being sent from
      # @return [Redrain::PaymentInitiateResponse]
      def initiate(amount:, wallet_address:, chain_id: nil)
        body = {
          "amount" => amount,
          "chainId" => chain_id,
          "walletAddress" => wallet_address
        }

        request(:post, "/payments", body: body, into: PaymentInitiateResponse)
      end
    end
  end
end
