# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.signatures+.
    #
    # Covers 2 endpoints: GET /signatures/payments, GET /signatures/withdrawals.
    class Signatures < Resource
      # Get payment signature for an authorized user tenant
      #
      # This endpoint retrieves the payment signature for an authorized user tenant. The
      # signature is used to authorize a payment transaction on a blockchain.
      #
      # GET /signatures/payments
      #
      # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
      #   deployed on. optional
      # @param [String] token The address of the token that the payment should be made in, as a
      #   hex string for EVM or base58 string for Solana
      # @param [String] amount The amount of token that is being paid
      # @param [String] admin_address The address of the admin making the payment, as a hex
      #   string for EVM or base58 string for Solana
      # @return [Redrain::IssuingSignature]
      def retrieve_payment_signature(token:, amount:, admin_address:, chain_id: nil)
        query = {
          "chainId" => chain_id,
          "token" => token,
          "amount" => amount,
          "adminAddress" => admin_address
        }

        request(:get, "/signatures/payments", query: query, into: IssuingSignature)
      end

      # Get withdrawal signature for an authorized user tenant
      #
      # This endpoint retrieves the withdrawal signature for an authorized user tenant. The
      # signature is used to authorize a withdrawal transaction on a blockchain.
      #
      # GET /signatures/withdrawals
      #
      # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
      #   deployed on. optional
      # @param [String] token The address of the token that the withdrawal should be made in, as
      #   a hex string for EVM or base58 string for Solana
      # @param [String] amount The amount of token that is being withdrawn
      # @param [String] admin_address The address of the admin making the payment, as a hex
      #   string for EVM or base58 string for Solana
      # @param [String] recipient_address The address the withdrawal should be sent to, as a hex
      #   string for EVM or base58 string for Solana
      # @return [Redrain::IssuingSignature]
      def retrieve_withdrawal_signature(
        token:,
        amount:,
        admin_address:,
        recipient_address:,
        chain_id: nil
      )
        query = {
          "chainId" => chain_id,
          "token" => token,
          "amount" => amount,
          "adminAddress" => admin_address,
          "recipientAddress" => recipient_address
        }

        request(:get, "/signatures/withdrawals", query: query, into: IssuingSignature)
      end
    end
  end
end
