# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.transactions+.
    #
    # Covers 4 endpoints: GET /transactions/:transactionId, PATCH /transactions/:transactionId,
    # GET /transactions, POST /transactions/:transactionId/disputes.
    class TransactionsResource < Resource
      # Backs +client.transactions.receipt+.
      #
      # Covers 2 endpoints: GET /transactions/:transactionId/receipt, PUT
      # /transactions/:transactionId/receipt.
      class ReceiptResource < Resource
        # Get a transaction's receipt
        #
        # This endpoint retrieves the receipt for a specific transaction. The receipt is
        # returned as a binary file, typically in PDF or similar format.
        #
        # GET /transactions/:transactionId/receipt
        #
        # @param [String] transaction_id the resource id
        # @return [String] the raw bytes of the response
        def retrieve(transaction_id)
          request(
            :get,
            path("/transactions/{transactionId}/receipt", transactionId: transaction_id),
            binary: true
          )
        end

        # Upload a transaction's receipt
        #
        # This endpoint allows you to upload a receipt for a specific transaction. The receipt
        # is provided as a binary file, typically in PDF format.
        #
        # PUT /transactions/:transactionId/receipt
        #
        # @param [String] transaction_id the resource id
        # @param [Redrain::Upload, File, String] receipt The receipt file to upload, typically
        #   in PDF or other binary formats
        # @return [nil] this endpoint returns no content
        def upload(transaction_id, receipt:)
          files = {
            "receipt" => receipt
          }

          request(
            :put,
            path("/transactions/{transactionId}/receipt", transactionId: transaction_id),
            files: files
          )
        end
      end

      include Redrain::Page
      sub_resource :receipt, ReceiptResource

      # Get a transaction by its id
      #
      # This endpoint retrieves a transaction by its unique ID. The transaction information
      # returned includes details such as the transaction type, amount, and status.
      #
      # GET /transactions/:transactionId
      #
      # @param [String] transaction_id the resource id
      # @return [Redrain::IssuingTransaction]
      def retrieve(transaction_id)
        request(
          :get,
          path("/transactions/{transactionId}", transactionId: transaction_id),
          into: IssuingTransaction
        )
      end

      # Update a transaction
      #
      # This endpoint allows updating a specific transaction by its ID. You can modify the
      # transaction's memo or other editable fields.
      #
      # PATCH /transactions/:transactionId
      #
      # @param [String] transaction_id the resource id
      # @param [String] memo A memo or note to attach to the transaction, providing additional
      #   information or context. optional
      # @return [nil] this endpoint returns no content
      def update(transaction_id, memo: nil)
        body = {
          "memo" => memo
        }

        request(
          :patch,
          path("/transactions/{transactionId}", transactionId: transaction_id),
          body: body
        )
      end

      # Get all transactions
      #
      # This endpoint retrieves all transactions associated with corporate cards, users, or
      # specific cards.
      #
      # GET /transactions
      #
      # @param [String] company_id For corporate cards, the identifier of the company to get
      #   transactions for. optional
      # @param [String] user_id The ID of the user to get transactions for. optional
      # @param [String] card_id The ID of the card to get transactions for. optional
      # @param [Array<String>] type The type of transactions to retrieve. optional
      # @param [String] transaction_hash The hash of the transaction to retrieve. optional
      # @param [Time, String] authorized_before Filter transactions authorized before a specific
      #   date. optional
      # @param [Time, String] authorized_after Filter transactions authorized after a specific
      #   date. optional
      # @param [Time, String] posted_before Filter transactions posted before a specific date.
      #   optional
      # @param [Time, String] posted_after Filter transactions posted after a specific date.
      #   optional
      # @param [String] cursor The ID of the resource after which to start fetching. optional
      # @param [Integer] limit The number of resources to fetch. optional
      # @return [Array<Redrain::IssuingTransaction>]
      def list(
        company_id: nil,
        user_id: nil,
        card_id: nil,
        type: nil,
        transaction_hash: nil,
        authorized_before: nil,
        authorized_after: nil,
        posted_before: nil,
        posted_after: nil,
        cursor: nil,
        limit: nil
      )
        query = {
          "companyId" => company_id,
          "userId" => user_id,
          "cardId" => card_id,
          "type" => type,
          "transactionHash" => transaction_hash,
          "authorizedBefore" => authorized_before,
          "authorizedAfter" => authorized_after,
          "postedBefore" => posted_before,
          "postedAfter" => posted_after,
          "cursor" => cursor,
          "limit" => limit
        }

        request(:get, "/transactions", query: query, into: [IssuingTransaction])
      end

      # Create a dispute for a transaction
      #
      # This endpoint allows the creation of a dispute for a specific transaction. The dispute
      # can include textual evidence to support the claim.
      #
      # POST /transactions/:transactionId/disputes
      #
      # @param [String] transaction_id the resource id
      # @param [String] text_evidence The textual evidence that supports the dispute. optional
      # @return [Redrain::IssuingDispute]
      def create_dispute(transaction_id, text_evidence: nil)
        body = {
          "textEvidence" => text_evidence
        }

        request(
          :post,
          path("/transactions/{transactionId}/disputes", transactionId: transaction_id),
          body: body,
          into: IssuingDispute
        )
      end
    end
  end
end
