# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

module Redrain
  # One class per node of Rain's resource tree, reachable from
  # {Redrain::Client}. Generated — see dev/generate.rb.
  module Resources
    # Backs +client.users+.
    #
    # Covers 10 endpoints: POST /users, GET /users/:userId, PATCH /users/:userId, GET /users,
    # DELETE /users/:userId, POST /users/:userId/cards, POST /users/:userId/charges, POST
    # /users/:userId/payments, GET /users/:userId/balances, GET /users/:userId/contracts.
    class Users < Resource
      # Backs +client.users.signatures+.
      #
      # Covers 2 endpoints: GET /users/:userId/signatures/payments, GET
      # /users/:userId/signatures/withdrawals.
      class Signatures < Resource
        # Get payment signature for a user
        #
        # This endpoint retrieves the payment signature for a specific user. The signature is
        # used to authorize a payment transaction for the user.
        #
        # GET /users/:userId/signatures/payments
        #
        # @param [String] user_id the resource id
        # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
        #   deployed on. optional
        # @param [String] token The address of the token that the payment should be made in, as
        #   a hex string for EVM or base58 string for Solana
        # @param [String] amount The amount of token that is being paid
        # @param [String] admin_address The address of the admin making the payment, as a hex
        #   string for EVM or base58 string for Solana
        # @return [Redrain::IssuingSignature]
        def retrieve_payment_signature(user_id, token:, amount:, admin_address:, chain_id: nil)
          query = {
            "chainId" => chain_id,
            "token" => token,
            "amount" => amount,
            "adminAddress" => admin_address
          }

          request(
            :get,
            path("/users/{userId}/signatures/payments", userId: user_id),
            query: query,
            into: IssuingSignature
          )
        end

        # Get withdrawal signature for a user
        #
        # This endpoint retrieves the withdrawal signature for a specific user. The signature is
        # required to authorize a withdrawal transaction for the user.
        #
        # GET /users/:userId/signatures/withdrawals
        #
        # @param [String] user_id the resource id
        # @param [Integer] chain_id The chain ID (base-10 number) that the smart contract is
        #   deployed on. optional
        # @param [String] token The address of the token that the withdrawal should be made in,
        #   as a hex string for EVM or base58 string for Solana
        # @param [String] amount The amount of token that is being withdrawn
        # @param [String] admin_address The address of the admin making the payment, as a hex
        #   string for EVM or base58 string for Solana
        # @param [String] recipient_address The address the withdrawal should be sent to, as a
        #   hex string for EVM or base58 string for Solana
        # @return [Redrain::IssuingSignature]
        def retrieve_withdrawal_signature(
          user_id,
          token:,
          amount:,
          admin_address:,
          recipient_address:,
          chain_id: nil
        )
          query = {
            "chainId" => chain_id,
            "token" => token,
            "amount" => amount,
            "adminAddress" => admin_address,
            "recipientAddress" => recipient_address
          }

          request(
            :get,
            path("/users/{userId}/signatures/withdrawals", userId: user_id),
            query: query,
            into: IssuingSignature
          )
        end
      end

      include Redrain::Page
      sub_resource :signatures, Signatures

      # Create an authorized user
      #
      # This endpoint allows the creation of a new authorized user with the necessary personal
      # details, including contact and wallet information.
      #
      # POST /users
      #
      # @param [String] first_name The user's first name
      # @param [String] last_name The user's last name
      # @param [String] email The user's email address
      # @param [String] wallet_address The user's wallet address. optional
      # @param [Hash] address Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @param [String] phone_country_code The user's phone country code. optional
      # @param [String] phone_number The user's phone number. optional
      # @return [Redrain::IssuingUser]
      def create(
        first_name:,
        last_name:,
        email:,
        wallet_address: nil,
        address: nil,
        phone_country_code: nil,
        phone_number: nil
      )
        body = {
          "firstName" => first_name,
          "lastName" => last_name,
          "email" => email,
          "walletAddress" => wallet_address,
          "address" => address,
          "phoneCountryCode" => phone_country_code,
          "phoneNumber" => phone_number
        }

        request(:post, "/users", body: body, into: IssuingUser)
      end

      # Get a user by id
      #
      # This endpoint retrieves a specific user by their unique ID. The user details, including
      # contact and wallet information, are returned.
      #
      # GET /users/:userId
      #
      # @param [String] user_id the resource id
      # @return [Redrain::IssuingUser]
      def retrieve(user_id)
        request(:get, path("/users/{userId}", userId: user_id), into: IssuingUser)
      end

      # Update a user
      #
      # This endpoint allows the update of a specific user's information, such as their name,
      # email, and contact details.
      #
      # PATCH /users/:userId
      #
      # @param [String] user_id the resource id
      # @param [String] first_name The user's first name. optional
      # @param [String] last_name The user's last name. optional
      # @param [String] email The user's email address. optional
      # @param [Boolean] is_active Indicates whether the user is active. optional
      # @param [Boolean] is_terms_of_service_accepted Indicates whether the user has accepted
      #   the terms of service. optional
      # @param [Hash] address Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @param [String] phone_country_code The user's phone country code. optional
      # @param [String] phone_number The user's phone number. optional
      # @return [Redrain::IssuingUser]
      def update(
        user_id,
        first_name: nil,
        last_name: nil,
        email: nil,
        is_active: nil,
        is_terms_of_service_accepted: nil,
        address: nil,
        phone_country_code: nil,
        phone_number: nil
      )
        body = {
          "firstName" => first_name,
          "lastName" => last_name,
          "email" => email,
          "isActive" => is_active,
          "isTermsOfServiceAccepted" => is_terms_of_service_accepted,
          "address" => address,
          "phoneCountryCode" => phone_country_code,
          "phoneNumber" => phone_number
        }

        request(:patch, path("/users/{userId}", userId: user_id), body: body, into: IssuingUser)
      end

      # Get all users
      #
      # This endpoint retrieves all users associated with a specific company. The response will
      # return a list of users, including their personal and contact details.
      #
      # GET /users
      #
      # @param [String] company_id For corporate cards, the identifier of the company to get
      #   users for. optional
      # @param [String] cursor The ID of the resource after which to start fetching. optional
      # @param [Integer] limit The number of resources to fetch. optional
      # @return [Array<Redrain::IssuingUser>]
      def list(company_id: nil, cursor: nil, limit: nil)
        query = {
          "companyId" => company_id,
          "cursor" => cursor,
          "limit" => limit
        }

        request(:get, "/users", query: query, into: [IssuingUser])
      end

      # Delete a user
      #
      # This endpoint deletes a user by their unique ID. Once deleted, the user will no longer
      # have access to the system.
      #
      # DELETE /users/:userId
      #
      # @param [String] user_id the resource id
      # @return [nil] this endpoint returns no content
      def delete(user_id)
        request(:delete, path("/users/{userId}", userId: user_id))
      end

      # Create a card for a user
      #
      # This endpoint allows the creation of a card for a specific user. The card can either be
      # physical or virtual and can include various configuration options such as the display
      # name and limit.
      #
      # POST /users/:userId/cards
      #
      # @param [String] user_id the resource id
      # @param [String] type one of: physical, virtual
      # @param [String] status The current status of the card. one of: notActivated, active,
      #   locked, canceled. optional
      # @param [Hash] limit Represents the spending limit and frequency for a card. optional
      # @param [Hash] configuration Configuration details for the card, including display name,
      #   product ID, and virtual card art. optional
      # @param [Hash] shipping optional
      # @param [Hash] billing Represents a physical address with components like street, city,
      #   region, postal code, and country. optional
      # @return [Redrain::IssuingCard]
      def create_card(
        user_id,
        type:,
        status: nil,
        limit: nil,
        configuration: nil,
        shipping: nil,
        billing: nil
      )
        body = {
          "type" => type,
          "status" => status,
          "limit" => limit,
          "configuration" => configuration,
          "shipping" => shipping,
          "billing" => billing
        }

        request(
          :post,
          path("/users/{userId}/cards", userId: user_id),
          body: body,
          into: IssuingCard
        )
      end

      # Charge a user a custom fee
      #
      # This endpoint allows creating a custom fee charge for a specific user. The fee can be
      # defined in the request body along with its details.
      #
      # POST /users/:userId/charges
      #
      # @param [String] user_id the resource id
      # @param [Integer] amount The amount of the charge, in cents
      # @param [String] description The description of the charge
      # @return [Redrain::IssuingChargeCreateChargeResponse]
      def create_charge(user_id, amount:, description:)
        body = {
          "amount" => amount,
          "description" => description
        }

        request(
          :post,
          path("/users/{userId}/charges", userId: user_id),
          body: body,
          into: IssuingChargeCreateChargeResponse
        )
      end

      # Initiate a payment for a user
      #
      # This endpoint allows initiating a payment for a specific user. The payment is made from
      # the user's wallet address to the specified recipient address.
      #
      # POST /users/:userId/payments
      #
      # @param [String] user_id the resource id
      # @param [Integer] amount The amount of the payment, in cents
      # @param [Integer] chain_id The chain ID (base-10 number) that the payment transaction is
      #   on. optional
      # @param [String] wallet_address The wallet address the payment is being sent from
      # @return [Redrain::UserInitiatePaymentResponse]
      def initiate_payment(user_id, amount:, wallet_address:, chain_id: nil)
        body = {
          "amount" => amount,
          "chainId" => chain_id,
          "walletAddress" => wallet_address
        }

        request(
          :post,
          path("/users/{userId}/payments", userId: user_id),
          body: body,
          into: UserInitiatePaymentResponse
        )
      end

      # Get a users's credit balances
      #
      # This endpoint retrieves the credit balances for a specific user. It provides information
      # about the user's credit limit, pending charges, posted charges, balance due, and
      # spending power.
      #
      # GET /users/:userId/balances
      #
      # @param [String] user_id the resource id
      # @return [Redrain::UserRetrieveBalancesResponse]
      def retrieve_balances(user_id)
        request(
          :get,
          path("/users/{userId}/balances", userId: user_id),
          into: UserRetrieveBalancesResponse
        )
      end

      # Get smart contract information for a user
      #
      # This endpoint retrieves smart contract information for a specific user. It returns a
      # list of contracts associated with the user.
      #
      # GET /users/:userId/contracts
      #
      # @param [String] user_id the resource id
      # @return [Array<Redrain::IssuingContract>]
      def retrieve_contracts(user_id)
        request(
          :get,
          path("/users/{userId}/contracts", userId: user_id),
          into: [IssuingContract]
        )
      end
    end
  end
end
