# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class ApplicationsResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_applications_company_create
    stub = stub_api(:post, "/applications/company", sends: { "initialUser" => "00000000-0000-4000-8000-000000000000", "name" => "00000000-0000-4000-8000-000000000000", "address" => "00000000-0000-4000-8000-000000000000", "entity" => "00000000-0000-4000-8000-000000000000", "representatives" => "00000000-0000-4000-8000-000000000000", "ultimateBeneficialOwners" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.applications.company.create(initial_user: "00000000-0000-4000-8000-000000000000", name: "00000000-0000-4000-8000-000000000000", address: "00000000-0000-4000-8000-000000000000", entity: "00000000-0000-4000-8000-000000000000", representatives: "00000000-0000-4000-8000-000000000000", ultimate_beneficial_owners: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_applications_company_retrieve
    stub = stub_api(:get, "/applications/company/00000000-0000-4000-8000-000000000000", body: {})

    result = client.applications.company.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::CompanyRetrieveResponse, result
  end

  def test_applications_company_update
    stub = stub_api(:patch, "/applications/company/00000000-0000-4000-8000-000000000000", body: {})

    result = client.applications.company.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_applications_company_reapply
    stub = stub_api(:put, "/applications/company/00000000-0000-4000-8000-000000000000/reapply", sends: { "initialUser" => "00000000-0000-4000-8000-000000000000", "name" => "00000000-0000-4000-8000-000000000000", "address" => "00000000-0000-4000-8000-000000000000", "entity" => "00000000-0000-4000-8000-000000000000", "representatives" => "00000000-0000-4000-8000-000000000000", "ultimateBeneficialOwners" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.applications.company.reapply("00000000-0000-4000-8000-000000000000", initial_user: "00000000-0000-4000-8000-000000000000", name: "00000000-0000-4000-8000-000000000000", address: "00000000-0000-4000-8000-000000000000", entity: "00000000-0000-4000-8000-000000000000", representatives: "00000000-0000-4000-8000-000000000000", ultimate_beneficial_owners: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_applications_company_upload_document
    stub = stub_api(:put, "/applications/company/00000000-0000-4000-8000-000000000000/document", status: 204)

    result = client.applications.company.upload_document("00000000-0000-4000-8000-000000000000", document: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end

  def test_applications_company_ubo_update
    stub = stub_api(:patch, "/applications/company/00000000-0000-4000-8000-000000000000/ubo/00000000-0000-4000-8000-000000000000", body: {})

    result = client.applications.company.ubo.update("00000000-0000-4000-8000-000000000000", company_id: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_applications_company_ubo_upload_document
    stub = stub_api(:put, "/applications/company/00000000-0000-4000-8000-000000000000/ubo/document", status: 204)

    result = client.applications.company.ubo.upload_document("00000000-0000-4000-8000-000000000000", email: "00000000-0000-4000-8000-000000000000", document: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end

  def test_applications_company_ubo_document_upload
    stub = stub_api(:put, "/applications/company/00000000-0000-4000-8000-000000000000/ubo/00000000-0000-4000-8000-000000000000/document", status: 204)

    result = client.applications.company.ubo.document.upload("00000000-0000-4000-8000-000000000000", company_id: "00000000-0000-4000-8000-000000000000", document: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end

  def test_applications_user_create
    stub = stub_api(:post, "/applications/user", sends: { "ipAddress" => "00000000-0000-4000-8000-000000000000", "occupation" => "00000000-0000-4000-8000-000000000000", "annualSalary" => "00000000-0000-4000-8000-000000000000", "accountPurpose" => "00000000-0000-4000-8000-000000000000", "expectedMonthlyVolume" => "00000000-0000-4000-8000-000000000000", "isTermsOfServiceAccepted" => true }, body: {})

    result = client.applications.user.create(ip_address: "00000000-0000-4000-8000-000000000000", occupation: "00000000-0000-4000-8000-000000000000", annual_salary: "00000000-0000-4000-8000-000000000000", account_purpose: "00000000-0000-4000-8000-000000000000", expected_monthly_volume: "00000000-0000-4000-8000-000000000000", is_terms_of_service_accepted: true)

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_applications_user_retrieve
    stub = stub_api(:get, "/applications/user/00000000-0000-4000-8000-000000000000", body: {})

    result = client.applications.user.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::UserRetrieveResponse, result
  end

  def test_applications_user_update
    stub = stub_api(:patch, "/applications/user/00000000-0000-4000-8000-000000000000", body: {})

    result = client.applications.user.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_applications_user_initiate
    stub = stub_api(:post, "/applications/user/initiate", body: {})

    result = client.applications.user.initiate

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_applications_user_reapply
    stub = stub_api(:put, "/applications/user/00000000-0000-4000-8000-000000000000/reapply", sends: { "birthDate" => "00000000-0000-4000-8000-000000000000", "nationalId" => "00000000-0000-4000-8000-000000000000", "countryOfIssue" => "00000000-0000-4000-8000-000000000000", "address" => "00000000-0000-4000-8000-000000000000", "ipAddress" => "00000000-0000-4000-8000-000000000000", "occupation" => "00000000-0000-4000-8000-000000000000", "annualSalary" => "00000000-0000-4000-8000-000000000000", "accountPurpose" => "00000000-0000-4000-8000-000000000000", "expectedMonthlyVolume" => "00000000-0000-4000-8000-000000000000", "isTermsOfServiceAccepted" => true }, body: {})

    result = client.applications.user.reapply("00000000-0000-4000-8000-000000000000", birth_date: "00000000-0000-4000-8000-000000000000", national_id: "00000000-0000-4000-8000-000000000000", country_of_issue: "00000000-0000-4000-8000-000000000000", address: "00000000-0000-4000-8000-000000000000", ip_address: "00000000-0000-4000-8000-000000000000", occupation: "00000000-0000-4000-8000-000000000000", annual_salary: "00000000-0000-4000-8000-000000000000", account_purpose: "00000000-0000-4000-8000-000000000000", expected_monthly_volume: "00000000-0000-4000-8000-000000000000", is_terms_of_service_accepted: true)

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_applications_user_upload_document
    stub = stub_api(:put, "/applications/user/00000000-0000-4000-8000-000000000000/document", status: 204)

    result = client.applications.user.upload_document("00000000-0000-4000-8000-000000000000", document: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end
end
