# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class BalancesResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_balances_retrieve
    stub = stub_api(:get, "/balances", body: {})

    result = client.balances.retrieve

    assert_requested(stub)
    assert_kind_of Redrain::BalanceRetrieveResponse, result
  end
end
