# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class CardsResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_cards_retrieve
    stub = stub_api(:get, "/cards/00000000-0000-4000-8000-000000000000", body: {})

    result = client.cards.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCard, result
  end

  def test_cards_update
    stub = stub_api(:patch, "/cards/00000000-0000-4000-8000-000000000000", body: {})

    result = client.cards.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCard, result
  end

  def test_cards_list
    stub = stub_api(:get, "/cards", body: [])

    result = client.cards.list

    assert_requested(stub)
    assert_equal [], result
  end

  def test_cards_retrieve_secrets
    stub = stub_api(:get, "/cards/00000000-0000-4000-8000-000000000000/secrets", body: {})

    result = client.cards.retrieve_secrets("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::CardRetrieveSecretsResponse, result
  end

  def test_cards_pin_retrieve
    stub = stub_api(:get, "/cards/00000000-0000-4000-8000-000000000000/pin", body: {})

    result = client.cards.pin.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::PinRetrieveResponse, result
  end

  def test_cards_pin_update
    stub = stub_api(:put, "/cards/00000000-0000-4000-8000-000000000000/pin", sends: { "encryptedPin" => "00000000-0000-4000-8000-000000000000" }, status: 204)

    result = client.cards.pin.update("00000000-0000-4000-8000-000000000000", encrypted_pin: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_nil result
  end
end
