# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class CompaniesResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_companies_retrieve
    stub = stub_api(:get, "/companies/00000000-0000-4000-8000-000000000000", body: {})

    result = client.companies.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_companies_update
    stub = stub_api(:patch, "/companies/00000000-0000-4000-8000-000000000000", body: {})

    result = client.companies.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCompany, result
  end

  def test_companies_list
    stub = stub_api(:get, "/companies", body: [])

    result = client.companies.list

    assert_requested(stub)
    assert_equal [], result
  end

  def test_companies_charge
    stub = stub_api(:post, "/companies/00000000-0000-4000-8000-000000000000/charges", sends: { "amount" => "00000000-0000-4000-8000-000000000000", "description" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.companies.charge("00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", description: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingChargeCreateChargeResponse, result
  end

  def test_companies_create_user
    stub = stub_api(:post, "/companies/00000000-0000-4000-8000-000000000000/users", sends: { "firstName" => "00000000-0000-4000-8000-000000000000", "lastName" => "00000000-0000-4000-8000-000000000000", "email" => "00000000-0000-4000-8000-000000000000", "isTermsOfServiceAccepted" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.companies.create_user("00000000-0000-4000-8000-000000000000", first_name: "00000000-0000-4000-8000-000000000000", last_name: "00000000-0000-4000-8000-000000000000", email: "00000000-0000-4000-8000-000000000000", is_terms_of_service_accepted: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_companies_initiate_payment
    stub = stub_api(:post, "/companies/00000000-0000-4000-8000-000000000000/payments", sends: { "amount" => "00000000-0000-4000-8000-000000000000", "walletAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.companies.initiate_payment("00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", wallet_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::CompanyInitiatePaymentResponse, result
  end

  def test_companies_retrieve_balances
    stub = stub_api(:get, "/companies/00000000-0000-4000-8000-000000000000/balances", body: {})

    result = client.companies.retrieve_balances("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::CompanyRetrieveBalancesResponse, result
  end

  def test_companies_retrieve_contracts
    stub = stub_api(:get, "/companies/00000000-0000-4000-8000-000000000000/contracts", body: [])

    result = client.companies.retrieve_contracts("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_equal [], result
  end

  def test_companies_signatures_retrieve_payment_signature
    stub = stub_api(:get, "/companies/00000000-0000-4000-8000-000000000000/signatures/payments", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.companies.signatures.retrieve_payment_signature("00000000-0000-4000-8000-000000000000", token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end

  def test_companies_signatures_retrieve_withdrawal_signature
    stub = stub_api(:get, "/companies/00000000-0000-4000-8000-000000000000/signatures/withdrawals", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000", "recipientAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.companies.signatures.retrieve_withdrawal_signature("00000000-0000-4000-8000-000000000000", token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000", recipient_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end
end
