# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class ContractsResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_contracts_list
    stub = stub_api(:get, "/contracts", body: [])

    result = client.contracts.list

    assert_requested(stub)
    assert_equal [], result
  end
end
