# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class DisputesResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_disputes_retrieve
    stub = stub_api(:get, "/disputes/00000000-0000-4000-8000-000000000000", body: {})

    result = client.disputes.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingDispute, result
  end

  def test_disputes_update
    stub = stub_api(:patch, "/disputes/00000000-0000-4000-8000-000000000000", status: 204)

    result = client.disputes.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_nil result
  end

  def test_disputes_list
    stub = stub_api(:get, "/disputes", body: [])

    result = client.disputes.list

    assert_requested(stub)
    assert_equal [], result
  end

  def test_disputes_evidence_list
    stub = stub_api(:get, "/disputes/00000000-0000-4000-8000-000000000000/evidence", body: BINARY_FIXTURE, content_type: "application/octet-stream")

    result = client.disputes.evidence.list("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_equal BINARY_FIXTURE, result
  end

  def test_disputes_evidence_upload
    stub = stub_api(:put, "/disputes/00000000-0000-4000-8000-000000000000/evidence", status: 204)

    result = client.disputes.evidence.upload("00000000-0000-4000-8000-000000000000", name: "00000000-0000-4000-8000-000000000000", type: "00000000-0000-4000-8000-000000000000", evidence: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end
end
