# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class KeysResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_keys_create
    stub = stub_api(:post, "/keys", sends: { "name" => "00000000-0000-4000-8000-000000000000", "expiresAt" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.keys.create(name: "00000000-0000-4000-8000-000000000000", expires_at: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingKey, result
  end

  def test_keys_delete
    stub = stub_api(:delete, "/keys/00000000-0000-4000-8000-000000000000", status: 204)

    result = client.keys.delete("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_nil result
  end
end
