# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class PaymentsResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_payments_initiate
    stub = stub_api(:post, "/payments", sends: { "amount" => "00000000-0000-4000-8000-000000000000", "walletAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.payments.initiate(amount: "00000000-0000-4000-8000-000000000000", wallet_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::PaymentInitiateResponse, result
  end
end
