# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class SignaturesResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_signatures_retrieve_payment_signature
    stub = stub_api(:get, "/signatures/payments", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.signatures.retrieve_payment_signature(token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end

  def test_signatures_retrieve_withdrawal_signature
    stub = stub_api(:get, "/signatures/withdrawals", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000", "recipientAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.signatures.retrieve_withdrawal_signature(token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000", recipient_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end
end
