# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class TransactionsResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_transactions_retrieve
    stub = stub_api(:get, "/transactions/00000000-0000-4000-8000-000000000000", body: {})

    result = client.transactions.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingTransaction, result
  end

  def test_transactions_update
    stub = stub_api(:patch, "/transactions/00000000-0000-4000-8000-000000000000", status: 204)

    result = client.transactions.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_nil result
  end

  def test_transactions_list
    stub = stub_api(:get, "/transactions", body: [])

    result = client.transactions.list

    assert_requested(stub)
    assert_equal [], result
  end

  def test_transactions_create_dispute
    stub = stub_api(:post, "/transactions/00000000-0000-4000-8000-000000000000/disputes", body: {})

    result = client.transactions.create_dispute("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingDispute, result
  end

  def test_transactions_receipt_retrieve
    stub = stub_api(:get, "/transactions/00000000-0000-4000-8000-000000000000/receipt", body: BINARY_FIXTURE, content_type: "application/octet-stream")

    result = client.transactions.receipt.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_equal BINARY_FIXTURE, result
  end

  def test_transactions_receipt_upload
    stub = stub_api(:put, "/transactions/00000000-0000-4000-8000-000000000000/receipt", status: 204)

    result = client.transactions.receipt.upload("00000000-0000-4000-8000-000000000000", receipt: upload_fixture)

    assert_requested(stub)
    assert_nil result
  end
end
