# frozen_string_literal: true
#
# Generated by `rake generate` from openapi/rain-issuing.json and
# dev/resource_map.yml. Do not edit — fix the generator instead.

require_relative "../test_helper"

class UsersResourceTest < Minitest::Test
  include ResourceTestHelper

  def test_users_create
    stub = stub_api(:post, "/users", sends: { "firstName" => "00000000-0000-4000-8000-000000000000", "lastName" => "00000000-0000-4000-8000-000000000000", "email" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.users.create(first_name: "00000000-0000-4000-8000-000000000000", last_name: "00000000-0000-4000-8000-000000000000", email: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_users_retrieve
    stub = stub_api(:get, "/users/00000000-0000-4000-8000-000000000000", body: {})

    result = client.users.retrieve("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_users_update
    stub = stub_api(:patch, "/users/00000000-0000-4000-8000-000000000000", body: {})

    result = client.users.update("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingUser, result
  end

  def test_users_list
    stub = stub_api(:get, "/users", body: [])

    result = client.users.list

    assert_requested(stub)
    assert_equal [], result
  end

  def test_users_delete
    stub = stub_api(:delete, "/users/00000000-0000-4000-8000-000000000000", status: 204)

    result = client.users.delete("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_nil result
  end

  def test_users_create_card
    stub = stub_api(:post, "/users/00000000-0000-4000-8000-000000000000/cards", sends: { "type" => "physical" }, body: {})

    result = client.users.create_card("00000000-0000-4000-8000-000000000000", type: "physical")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingCard, result
  end

  def test_users_create_charge
    stub = stub_api(:post, "/users/00000000-0000-4000-8000-000000000000/charges", sends: { "amount" => "00000000-0000-4000-8000-000000000000", "description" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.users.create_charge("00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", description: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingChargeCreateChargeResponse, result
  end

  def test_users_initiate_payment
    stub = stub_api(:post, "/users/00000000-0000-4000-8000-000000000000/payments", sends: { "amount" => "00000000-0000-4000-8000-000000000000", "walletAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.users.initiate_payment("00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", wallet_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::UserInitiatePaymentResponse, result
  end

  def test_users_retrieve_balances
    stub = stub_api(:get, "/users/00000000-0000-4000-8000-000000000000/balances", body: {})

    result = client.users.retrieve_balances("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::UserRetrieveBalancesResponse, result
  end

  def test_users_retrieve_contracts
    stub = stub_api(:get, "/users/00000000-0000-4000-8000-000000000000/contracts", body: [])

    result = client.users.retrieve_contracts("00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_equal [], result
  end

  def test_users_signatures_retrieve_payment_signature
    stub = stub_api(:get, "/users/00000000-0000-4000-8000-000000000000/signatures/payments", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.users.signatures.retrieve_payment_signature("00000000-0000-4000-8000-000000000000", token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end

  def test_users_signatures_retrieve_withdrawal_signature
    stub = stub_api(:get, "/users/00000000-0000-4000-8000-000000000000/signatures/withdrawals", query: { "token" => "00000000-0000-4000-8000-000000000000", "amount" => "00000000-0000-4000-8000-000000000000", "adminAddress" => "00000000-0000-4000-8000-000000000000", "recipientAddress" => "00000000-0000-4000-8000-000000000000" }, body: {})

    result = client.users.signatures.retrieve_withdrawal_signature("00000000-0000-4000-8000-000000000000", token: "00000000-0000-4000-8000-000000000000", amount: "00000000-0000-4000-8000-000000000000", admin_address: "00000000-0000-4000-8000-000000000000", recipient_address: "00000000-0000-4000-8000-000000000000")

    assert_requested(stub)
    assert_kind_of Redrain::IssuingSignature, result
  end
end
