# frozen_string_literal: true

module Generator
  # Shared plumbing for the three writers: banner, comment wrapping, and
  # writing files only when their contents actually changed (so `rake generate`
  # doesn't churn mtimes and stays cheap to run in a loop).
  module Writer
    BANNER = <<~TEXT
      # frozen_string_literal: true
      #
      # Generated by `rake generate` from openapi/rain-issuing.json and
      # dev/resource_map.yml. Do not edit — fix the generator instead.
    TEXT

    WIDTH = 96

    def write_file(path, contents)
      FileUtils.mkdir_p(File.dirname(path))
      # Indenting a heredoc leaves whitespace on its blank lines; strip it here
      # once rather than in every emitter.
      contents = "#{contents.lines.map(&:rstrip).join("\n").rstrip}\n"
      return if File.exist?(path) && File.read(path) == contents

      File.write(path, contents)
    end

    # Clears out stale generated files so a removed endpoint doesn't leave an
    # orphan behind that still loads and still looks real.
    def prune(dir, keep)
      return unless Dir.exist?(dir)

      Dir.glob(File.join(dir, "**", "*.rb")).each do |path|
        File.delete(path) unless keep.include?(File.expand_path(path))
      end
      Dir.glob(File.join(dir, "**", "*")).select { |p| File.directory?(p) }
         .sort_by { |p| -p.length }
         .each { |p| Dir.rmdir(p) if Dir.empty?(p) }
    end

    def comment(text, indent: "")
      return [] if text.nil? || text.strip.empty?

      wrap(text.strip.gsub(/\s+/, " "), WIDTH - indent.length - 2).map { |line| "#{indent}# #{line}".rstrip }
    end

    def wrap(text, width)
      text.split(" ").each_with_object([+""]) do |word, lines|
        if lines.last.empty?
          lines[-1] = word.dup
        elsif lines.last.length + 1 + word.length <= width
          lines[-1] << " " << word
        else
          lines << word.dup
        end
      end
    end

    # %w[] when every value is a bare word, otherwise a plain array literal.
    def literal_array(values)
      return "%w[#{values.join(" ")}]" if values.all? { |v| v.is_a?(String) && v.match?(/\A[\w.-]+\z/) }

      "[#{values.map(&:inspect).join(", ")}]"
    end
  end
end
